apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: automation-cluster-boot-onprem-rauto-1010
  project: defaultproject
spec:
  blueprint:
    name: default
    version: latest
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.32.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: automation-cluster-boot-master-onprem-1010-1
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.12
      roles:
      - Worker
      - ControlPlane
    platformVersion: v1.1.0
  proxy: {}
  type: mks
