apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: automation-cluster-boot-onprem-rauto-9717
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.32.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    platformVersion: v1.1.0
  sharing:
    enabled: true
    projects:
    - name: rauto-infra-test-project
    - name: rauto-platform-test-project
  type: mks
