apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    role: automation
    team: rafay-infra
  name: cli-aksrauto-868934224
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-8980547
    version: v2
  cloudCredentials: cli-cprauto-938851299
  config:
    kind: aksClusterConfig
    metadata:
      name: cli-aksrauto-868934224
    spec:
      maintenanceConfigurations:
      - apiVersion: "2024-01-01"
        name: aksManagedAutoUpgradeSchedule
        properties:
          maintenanceWindow:
            durationHours: 4
            schedule:
              weekly:
                dayOfWeek: Tuesday
                intervalWeeks: 1
            startDate: "2024-07-16"
            startTime: "18:34"
            utcOffset: "+05:30"
        type: Microsoft.ContainerService/managedClusters/maintenanceConfigurations
      - apiVersion: "2024-01-01"
        name: aksManagedNodeOSUpgradeSchedule
        properties:
          maintenanceWindow:
            durationHours: 4
            schedule:
              weekly:
                dayOfWeek: Tuesday
                intervalWeeks: 1
            startDate: "2024-07-16"
            startTime: "18:34"
            utcOffset: "+05:30"
        type: Microsoft.ContainerService/managedClusters/maintenanceConfigurations
      managedCluster:
        apiVersion: "2021-05-01"
        identity:
          type: SystemAssigned
        location: northcentralus
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          autoUpgradeProfile:
            nodeOsUpgradeChannel: NodeImage
            upgradeChannel: stable
          disableLocalAccounts: false
          dnsPrefix: cli-aksrauto-868934224-dns
          enablePodSecurityPolicy: false
          kubernetesVersion: 1.33.5
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Running
        sku:
          name: Basic
          tier: Free
        tags:
          migrationtag: migratevalue
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2021-05-01"
        location: northcentralus
        name: pool1
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          nodeLabels:
            pool1migratekey: poool1migratevalue
          orchestratorVersion: 1.33.4
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  proxyConfig: {}
  type: aks
