apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    role: gk-qe
    team: rafay-infra
  name: cli-aksrauto-919271066
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-4544171
    version: v2
  cloudCredentials: cli-cprauto-373363456
  config:
    kind: aksClusterConfig
    metadata:
      name: cli-aksrauto-919271066
    spec:
      managedCluster:
        apiVersion: "2021-05-01"
        identity:
          type: SystemAssigned
        location: northcentralus
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: cli-aksrauto-919271066-dns
          enablePodSecurityPolicy: false
          kubernetesVersion: 1.33.4
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
        sku:
          name: Basic
          tier: Free
        tags:
          migrationtag: migratevalue
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2021-05-01"
        location: northcentralus
        name: pool1
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 1
          mode: System
          nodeLabels:
            pool1migratekey: poool1migratevalue
          orchestratorVersion: 1.33.4
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  proxyConfig: {}
  type: aks
