apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    rauto: "true"
  name: cli-rauto-fw-cluster-57739115
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto_915951126
  config:
    controlPlaneVersion: "1.31"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-c
      type: zonal
    network:
      access:
        config:
          controlPlaneIPRange: 172.16.0.160/28
          disableSNAT: true
          enableAccessControlPlaneExternalIP: true
          enableAccessControlPlaneGlobal: true
          firewallRules:
          - action: ALLOW
            description: Allow Webhook Connections
            destinationRanges:
            - 172.16.8.48/28
            direction: EGRESS
            name: rauto-allow-egress
            priority: 1555
            rules:
            - ports:
              - "22284"
              - "9447"
              protocol: tcp
        type: private
      dataPlaneV2: ADVANCED_DATAPATH
      enableDataPlaneV2Metrics: true
      enableDataPlaneV2Observability: true
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.31"
      size: 1
      upgradeSettings:
        config:
          maxSurge: 1
        strategy: SURGE
  type: gke
