apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-os-529341616
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: cli-cprauto-529341616
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: automationuser
        principalARN: arn:aws:iam::211125364662:user/kalyan@rafay.co
        type: STANDARD
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: eks-pod-identity-agent
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    addonsConfig:
      disableEBSCSIDriver: true
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    iam:
      serviceAccounts:
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-irsa
          labels:
            irsalabel: rauto-irsalabel
          name: rauto-irsa
          namespace: rafay-system
        tags:
          irsatag: rauto-irsatag
      withOIDC: true
    managedNodeGroups:
    - amiFamily: Ubuntu2404
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.medium
      maxSize: 1
      minSize: 1
      name: ng-defaultami-managed-ubuntu2404
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.medium
      maxSize: 1
      minSize: 1
      name: ng-defaultami-managed-AmazonLinux2023
      volumeSize: 80
      volumeType: gp3
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.medium
      maxSize: 1
      minSize: 1
      name: ng-defaultami-managed-br
      volumeSize: 80
      volumeType: gp3
    - ami: ami-099af0196b2d0ff43
      desiredCapacity: 1
      instanceType: t3.xlarge
      name: cli-managed-ng-1-529341616
      overrideBootstrapCommand: '| [Bottlerocket]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
    - ami: ami-01493046d3cff1aba
      desiredCapacity: 1
      instanceType: t3.xlarge
      name: cli-managed-ng-2-529341616
      overrideBootstrapCommand: '| [AmazonLinux2023]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
    - ami: ami-0ad0f739ba9218571
      desiredCapacity: 1
      instanceType: t3.xlarge
      name: cli-managed-ng-3-529341616
      overrideBootstrapCommand: '| [Ubuntu2404]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
    metadata:
      name: cli-eksrauto-os-529341616
      region: us-east-1
      tags:
        build_num: local
        creation_time: "2026-01-12T07:14:48Z"
        email: automation@rafay.co
        env: automation
        squad: local
      version: "1.33"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: Ubuntu2404
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instancesDistribution:
        instanceTypes:
        - t3.medium
      maxSize: 1
      minSize: 1
      name: ng-self-def-Ubuntu2404
      volumeSize: 80
      volumeType: gp3
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instancesDistribution:
        instanceTypes:
        - t3.medium
      maxSize: 1
      minSize: 1
      name: ng-self-def-Bottlerocket
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instancesDistribution:
        instanceTypes:
        - t3.medium
      maxSize: 1
      minSize: 1
      name: ng-self-def-AmazonLinux2023
      volumeSize: 80
      volumeType: gp3
    - ami: ami-099af0196b2d0ff43
      desiredCapacity: 1
      instanceType: t3.xlarge
      name: cli-self-managed-ng-1-529341616
      overrideBootstrapCommand: '| [Bottlerocket]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
    - ami: ami-0b643482870c8f6db
      desiredCapacity: 1
      instanceType: t3.xlarge
      name: cli-self-managed-ng-2-529341616
      overrideBootstrapCommand: '| [AmazonLinux2023]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
    - ami: ami-068ba406f08e8c28f
      desiredCapacity: 1
      instanceType: t3.xlarge
      name: cli-self-managed-ng-3-529341616
      overrideBootstrapCommand: '| [Ubuntu2404]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
