apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-707713622
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: cli-cprauto-707713622
  config:
    addons:
    - configurationValues: '{"enableWindowsIpam":"true"}'
      name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    managedNodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3a.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-first-707713622
      privateNetworking: true
      version: "1.33"
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3a.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-second-707713622
      privateNetworking: true
      version: "1.33"
    metadata:
      name: cli-eksrauto-707713622
      region: us-east-1
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.33"
    network:
      cni:
        name: aws-cni
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private: {}
        public: {}
  type: aws-eks
