apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-236806122
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: cprauto-236806122
  config:
    addons:
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    managedNodeGroups:
    - instanceTypes:
      - t3a.xlarge
      - t3.xlarge
      name: cli-awsngrauto-236806122
      privateNetworking: true
      spot: true
      version: "1.34"
    metadata:
      name: cli-eksrauto-236806122
      region: us-east-1
      tags:
        build_num: master-sanity-master-98
        creation_time: "2025-11-27T02:28:31Z"
        email: automation@rafay.co
        env: automation
        squad: vikings
      version: "1.34"
    nodeGroups:
    - desiredCapacity: 1
      instancesDistribution:
        instanceTypes:
        - t3a.xlarge
        - t3.xlarge
        maxPrice: 0.7
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2
      name: cli-selfngrauto-236806122
      privateNetworking: true
      version: "1.34"
    - desiredCapacity: 1
      instancesDistribution:
        instanceTypes:
        - t3.xlarge
        - t3a.xlarge
        maxPrice: 0.75
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: lowest-price
        spotInstancePools: 3
      name: eksng2rauto-2701000
      privateNetworking: true
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
