apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: eks-import-system-component
  project: defaultproject
spec:
  blueprintConfig:
    name: amarbp
    version: v1
  cloudCredentials: rauto_139113044
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterInsightsPolicy
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEventPolicy
        kubernetesGroups:
        - eks:managed
        kubernetesUsername: arn:aws:sts::211125364662:assumed-role/AWSServiceRoleForAmazonEKS/{{SessionName}}
        principalARN: arn:aws:iam::211125364662:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
        type: STANDARD
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-nodegroup-NodeInstanceRole-fm3y6jc6xblz
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-nodegroup-NodeInstanceRole-knCRaXo0epz1
        type: EC2_LINUX
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/amarnath.savalgi@rafay.co
        principalARN: arn:aws:iam::211125364662:user/amarnath.savalgi@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/automation-user@rafay.co
        principalARN: arn:aws:iam::211125364662:user/automation-user@rafay.co
        type: STANDARD
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.32.6-eksbuild.12
    - name: metrics-server
      version: v0.8.0-eksbuild.5
    - name: vpc-cni
      serviceAccountRoleARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-addon-vpc-cni-Role1-YiNHhjAtYHMw
      version: v1.20.5-eksbuild.1
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1d
    iam:
      serviceAccounts:
      - metadata:
          name: default
          namespace: default
      - metadata:
          name: default
          namespace: kube-node-lease
      - metadata:
          name: default
          namespace: kube-public
      - metadata:
          name: attachdetach-controller
          namespace: kube-system
      - metadata:
          name: aws-cloud-provider
          namespace: kube-system
      - attachRoleARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-addon-vpc-cni-Role1-YiNHhjAtYHMw
        metadata:
          labels:
            app.kubernetes.io/instance: aws-vpc-cni
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: aws-node
            app.kubernetes.io/version: v1.20.5
            helm.sh/chart: aws-vpc-cni-1.20.5
            k8s-app: aws-node
          name: aws-node
          namespace: kube-system
        tags:
          alpha.eksctl.io/addon-name: vpc-cni
          alpha.eksctl.io/cluster-name: custom-cni-15-dec
          alpha.eksctl.io/eksctl-version: 0.217.0
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: custom-cni-15-dec
      - metadata:
          name: certificate-controller
          namespace: kube-system
      - metadata:
          name: clusterrole-aggregation-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: coredns
            k8s-app: kube-dns
          name: coredns
          namespace: kube-system
      - metadata:
          name: cronjob-controller
          namespace: kube-system
      - metadata:
          name: daemon-set-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: kube-system
      - metadata:
          name: deployment-controller
          namespace: kube-system
      - metadata:
          name: disruption-controller
          namespace: kube-system
      - metadata:
          name: endpoint-controller
          namespace: kube-system
      - metadata:
          name: endpointslice-controller
          namespace: kube-system
      - metadata:
          name: endpointslicemirroring-controller
          namespace: kube-system
      - metadata:
          name: ephemeral-volume-controller
          namespace: kube-system
      - metadata:
          name: expand-controller
          namespace: kube-system
      - metadata:
          name: generic-garbage-collector
          namespace: kube-system
      - metadata:
          name: horizontal-pod-autoscaler
          namespace: kube-system
      - metadata:
          name: job-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: kube-proxy
            k8s-app: kube-proxy
          name: kube-proxy
          namespace: kube-system
      - metadata:
          name: legacy-service-account-token-cleaner
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: metrics-server
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: metrics-server
            app.kubernetes.io/version: 0.7.2
          name: metrics-server
          namespace: kube-system
      - metadata:
          name: namespace-controller
          namespace: kube-system
      - metadata:
          name: node-controller
          namespace: kube-system
      - metadata:
          name: persistent-volume-binder
          namespace: kube-system
      - metadata:
          name: pod-garbage-collector
          namespace: kube-system
      - metadata:
          name: pv-protection-controller
          namespace: kube-system
      - metadata:
          name: pvc-protection-controller
          namespace: kube-system
      - metadata:
          name: replicaset-controller
          namespace: kube-system
      - metadata:
          name: replication-controller
          namespace: kube-system
      - metadata:
          name: resourcequota-controller
          namespace: kube-system
      - metadata:
          name: root-ca-cert-publisher
          namespace: kube-system
      - metadata:
          name: service-account-controller
          namespace: kube-system
      - metadata:
          name: service-controller
          namespace: kube-system
      - metadata:
          name: statefulset-controller
          namespace: kube-system
      - metadata:
          name: tagging-controller
          namespace: kube-system
      - metadata:
          name: ttl-after-finished-controller
          namespace: kube-system
      - metadata:
          name: ttl-controller
          namespace: kube-system
      - metadata:
          name: validatingadmissionpolicy-status-controller
          namespace: kube-system
      - metadata:
          name: volumeattributesclass-protection-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: ns-849158
      - metadata:
          annotations:
            meta.helm.sh/release-name: fluenttd
            meta.helm.sh/release-namespace: ns-849158
          labels:
            app.kubernetes.io/instance: fluenttd
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: fluentd
            app.kubernetes.io/version: v1.17.1
            helm.sh/chart: fluentd-0.5.3
            k8smgmt.io/project: defaultproject
            rep-addon: fluenttd
            rep-cluster: gkjwex2
            rep-cluster-name: eks-import-system-component
            rep-drift-reconcillation: disabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: 72dvp02
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: mpl1qx2
          name: fluenttd-fluentd
          namespace: ns-849158
      - metadata:
          labels:
            authz-expiry: "1765811628"
            authz-refreshed: "1765782828"
            k8smgmt.io/project: defaultproject
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: automation-45user-64rafay-46co
          name: automation-45user-64rafay-46co
          namespace: rafay-system
      - metadata:
          name: default
          namespace: rafay-system
      - metadata:
          annotations:
            meta.helm.sh/release-name: v2-ingress-infra
            meta.helm.sh/release-namespace: rafay-system
          labels:
            app.kubernetes.io/component: controller
            app.kubernetes.io/instance: v2-ingress-infra
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: ingress-nginx-v1
            app.kubernetes.io/version: 1.0.5
            helm.sh/chart: ingress-nginx-v1-4.0.8
            k8smgmt.io/project: defaultproject
            rep-addon: v2-ingress-infra
            rep-cluster: gkjwex2
            rep-cluster-name: eks-import-system-component
            rep-drift-reconcillation: disabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: 72dvp02
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: x28ooml
          name: ingress-controller-v1
          namespace: rafay-system
      - metadata:
          labels:
            authz-expiry: "1765811506"
            authz-refreshed: "1765782706"
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: rs-45admin-64rafay-46co
          name: rs-45admin-64rafay-46co
          namespace: rafay-system
      - metadata:
          labels:
            app.kubernetes.io/managed-by: Helm
            k8smgmt.io/project: defaultproject
            rep-addon: v2-infra
            rep-cluster: gkjwex2
            rep-cluster-name: eks-import-system-component
            rep-drift-reconcillation: disabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: 72dvp02
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: lk5xw2e
          name: system-sa
          namespace: rafay-system
      serviceRoleARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-cluster-ServiceRole-nyz1OT1Rg1Gb
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      - us-east-1d
      desiredCapacity: 2
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-nodegroup-NodeInstanceRole-fm3y6jc6xblz
      instanceType: t3.medium
      labels:
        alpha.eksctl.io/cluster-name: custom-cni-15-dec
        alpha.eksctl.io/nodegroup-name: ng-custom
      maxSize: 2
      minSize: 2
      name: ng-custom
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-098d935a91c5f12b2
      subnets:
      - subnet-07d5c518eb3f4b3fe
      - subnet-02df34e80bdac5aad
      tags:
        Name: eksctl-custom-cni-15-dec-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: custom-cni-15-dec
        alpha.eksctl.io/cluster-oidc-enabled: "true"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: ng-custom
        alpha.eksctl.io/nodegroup-type: managed
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: custom-cni-15-dec
        nodegroup: custom
      taints:
      - effect: NoSchedule
        key: dedicated
        value: "true"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      - us-east-1d
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-custom-cni-15-dec-nodegroup-NodeInstanceRole-knCRaXo0epz1
      instanceType: t3.medium
      labels:
        alpha.eksctl.io/cluster-name: custom-cni-15-dec
        alpha.eksctl.io/nodegroup-name: ng-nontainted
      maxSize: 1
      minSize: 1
      name: ng-nontainted
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-098d935a91c5f12b2
      subnets:
      - subnet-07d5c518eb3f4b3fe
      - subnet-02df34e80bdac5aad
      tags:
        Name: eksctl-custom-cni-15-dec-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: custom-cni-15-dec
        alpha.eksctl.io/cluster-oidc-enabled: "true"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: ng-nontainted
        alpha.eksctl.io/nodegroup-type: managed
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: custom-cni-15-dec
        nodegroup: custom
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: custom-cni-15-dec
      region: us-east-1
      tags:
        Name: eksctl-custom-cni-15-dec-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: custom-cni-15-dec
        alpha.eksctl.io/cluster-oidc-enabled: "true"
        alpha.eksctl.io/eksctl-version: 0.217.0
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: custom-cni-15-dec
      version: "1.32"
    network:
      cni:
        name: aws-cni
        params:
          customCniCrdSpec:
            us-east-1a:
            - securityGroups:
              - sg-098d935a91c5f12b2
              subnet: subnet-0ecdf4889ebdf048e
            us-east-1d:
            - securityGroups:
              - sg-098d935a91c5f12b2
              subnet: subnet-0e3890c37e69ede62
    vpc:
      cidr: 10.0.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      id: vpc-0a9b1edce7729b24e
      securityGroup: sg-0e1e4ba9e60376e83
      sharedNodeSecurityGroup: sg-098d935a91c5f12b2
      subnets:
        private:
          subnet-02df34e80bdac5aad:
            id: subnet-02df34e80bdac5aad
          subnet-07d5c518eb3f4b3fe:
            id: subnet-07d5c518eb3f4b3fe
        public:
          subnet-009ba6d982a898a70:
            id: subnet-009ba6d982a898a70
          subnet-043687424c0974379:
            id: subnet-043687424c0974379
  proxyConfig: {}
  systemComponentsPlacement:
    daemonSetOverride:
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: "true"
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: "true"
  type: aws-eks
