apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: gke-1sj
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: rauto-gke-cp-85462760
  config:
    controlPlaneVersion: "1.31"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-west1-c
      type: zonal
    network:
      access:
        config:
          controlPlaneIPRange: 172.16.0.0/28
          disableSNAT: true
          enableAccessControlPlaneExternalIP: true
          enableAccessControlPlaneGlobal: true
          enablePrivateNodes: true
        type: private
      dataPlaneV2: ADVANCED_DATAPATH
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.31"
      size: 3
      upgradeSettings:
        config:
          maxSurge: 1
        strategy: SURGE
  type: gke
