apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: gke-cluster-782300740
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto-gke-cp-782300740
  config:
    controlPlaneVersion: "1.31"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-c
      defaultNodeLocations:
        enabled: true
        zones:
        - us-central1-c
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      podAddressRange: /14
      serviceAddressRange: /20
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 50
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-2
      name: default-nodepool
      nodeVersion: "1.31"
      size: 1
    - autoScaling:
        maxNodes: 1
        minNodes: 1
      machineConfig:
        bootDiskSize: 50
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-2
      name: second-nodepool
      nodeVersion: "1.31"
      size: 1
    preBootstrapCommands:
    - ""
    - ""
  type: gke
