apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: master-node-check
  project: defaultproject
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.32.9
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: manish-27-1
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.234
      roles:
      - ControlPlane
      - Worker
    - arch: amd64
      hostname: manish-24-2
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.35
      roles:
      - ControlPlane
      - Worker
    platformVersion: v1.1.0
  proxy: {}
  type: mks
