apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-aks-953299580
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-5087855
  cloudCredentials: rauto_215525797
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-aks-953299580
    spec:
      managedCluster:
        additionalMetadata:
          acrProfile:
            acrName: rautoacr
            resourceGroupName: qa-automation
        apiVersion: "2024-01-01"
        identity:
          type: UserAssigned
          userAssignedIdentities:
            ? /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-cluster-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-fnf-cluster-identity
            : {}
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: rauto-aks-953299580-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.33.1
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Stopped
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          orchestratorVersion: 1.33.1
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/qa-automation/providers/Microsoft.Network/virtualNetworks/rautoqa/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2024-01-01"
        name: rauto627
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: User
          nodeLabels:
            key: rauto
          nodeTaints:
          - nodetaint=rauto:NoSchedule
          orchestratorVersion: 1.33.1
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/qa-automation/providers/Microsoft.Network/virtualNetworks/rautoqa/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  systemComponentsPlacement:
    daemonSetOverride:
      tolerations:
      - operator: Exists
    nodeSelector:
      key: rauto
    tolerations:
    - effect: NoSchedule
      key: nodetaint
      operator: Equal
      value: rauto
  type: aks
