apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-import-3276
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-nps-bp-5110
    version: v1
  cloudCredentials: rauto_211599160
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterInsightsPolicy
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEventPolicy
        kubernetesGroups:
        - eks:managed
        kubernetesUsername: arn:aws:sts::211125364662:assumed-role/AWSServiceRoleForAmazonEKS/{{SessionName}}
        principalARN: arn:aws:iam::211125364662:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
        type: STANDARD
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-3276-nodeg-NodeInstanceRole-3525MaZVxSJM
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-3276-nodeg-NodeInstanceRole-Ud1m74DoRyey
        tags:
          Name: eksctl-rauto-eks-import-3276-nodegroup-ng1/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-3276
          alpha.eksctl.io/eksctl-version: 0.217.0
          alpha.eksctl.io/nodegroup-name: ng1
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-3276-nodegroup-ng1/dd84b9d0-dff5-11f0-aa10-1264a4fd176b
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-3276-nodegroup-ng1
          build_num: qc-stage-new-k8s-version-121
          creation_time: "2025-12-23T11:40:50Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-3276
          eksctl.io/v1alpha2/nodegroup-name: ng1
          email: automation@rafay.co
          env: automation
          squad: all
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-3276-nodeg-NodeInstanceRole-vBry4gLMJfYO
        tags:
          Name: eksctl-rauto-eks-import-3276-nodegroup-ng2/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-3276
          alpha.eksctl.io/eksctl-version: 0.217.0
          alpha.eksctl.io/nodegroup-name: ng2
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-3276-nodegroup-ng2/dd855610-dff5-11f0-a396-12f045afe4f1
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-3276-nodegroup-ng2
          build_num: qc-stage-new-k8s-version-121
          creation_time: "2025-12-23T11:40:50Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-3276
          eksctl.io/v1alpha2/nodegroup-name: ng2
          email: automation@rafay.co
          env: automation
          squad: all
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        - eks:kube-proxy-windows
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-3276-nodeg-NodeInstanceRole-xwsVl256JSys
        tags:
          Name: eksctl-rauto-eks-import-3276-nodegroup-eks-win-ngrauto/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-3276
          alpha.eksctl.io/eksctl-version: 0.217.0
          alpha.eksctl.io/nodegroup-name: eks-win-ngrauto
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-3276-nodegroup-eks-win-ngrauto/dd86b5a0-dff5-11f0-ae64-0afffa36ebb9
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-3276-nodegroup-eks-win-ngrauto
          build_num: qc-stage-new-k8s-version-121
          creation_time: "2025-12-23T11:40:50Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-3276
          eksctl.io/v1alpha2/nodegroup-name: eks-win-ngrauto
          email: automation@rafay.co
          env: automation
          squad: all
        type: EC2_WINDOWS
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/automation-user@rafay.co
        principalARN: arn:aws:iam::211125364662:user/automation-user@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: rautouser
        principalARN: arn:aws:iam::211125364662:user/kalyan@rafay.co
        tags:
          Name: eksctl-rauto-eks-import-3276-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-3276
          alpha.eksctl.io/eksctl-version: 0.217.0
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-3276-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V/80d59d30-dff5-11f0-89e2-0e1a27880e03
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-3276-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V
          build_num: qc-stage-new-k8s-version-121
          creation_time: "2025-12-23T11:40:50Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-3276
          email: automation@rafay.co
          env: automation
          squad: all
        type: STANDARD
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: v1.11.3-eksbuild.1
    - name: kube-proxy
      version: v1.31.10-eksbuild.12
    - name: metrics-server
      version: v0.8.0-eksbuild.6
    - name: vpc-cni
      version: v1.20.4-eksbuild.2
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1b
    - us-east-1a
    iam:
      serviceAccounts:
      - metadata:
          name: default
          namespace: default
      - metadata:
          name: default
          namespace: default-rafay-master-sanity-automation
      - metadata:
          name: default
          namespace: kube-node-lease
      - metadata:
          name: default
          namespace: kube-public
      - metadata:
          name: attachdetach-controller
          namespace: kube-system
      - metadata:
          name: aws-cloud-provider
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: aws-vpc-cni
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: aws-node
            app.kubernetes.io/version: v1.20.4
            helm.sh/chart: aws-vpc-cni-1.20.4
            k8s-app: aws-node
          name: aws-node
          namespace: kube-system
      - metadata:
          name: certificate-controller
          namespace: kube-system
      - metadata:
          name: clusterrole-aggregation-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: coredns
            k8s-app: kube-dns
          name: coredns
          namespace: kube-system
      - metadata:
          name: cronjob-controller
          namespace: kube-system
      - metadata:
          name: daemon-set-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: kube-system
      - metadata:
          name: deployment-controller
          namespace: kube-system
      - metadata:
          name: disruption-controller
          namespace: kube-system
      - metadata:
          name: endpoint-controller
          namespace: kube-system
      - metadata:
          name: endpointslice-controller
          namespace: kube-system
      - metadata:
          name: endpointslicemirroring-controller
          namespace: kube-system
      - metadata:
          name: ephemeral-volume-controller
          namespace: kube-system
      - metadata:
          name: expand-controller
          namespace: kube-system
      - metadata:
          name: generic-garbage-collector
          namespace: kube-system
      - metadata:
          name: horizontal-pod-autoscaler
          namespace: kube-system
      - metadata:
          name: job-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: kube-proxy
            k8s-app: kube-proxy
          name: kube-proxy
          namespace: kube-system
      - metadata:
          name: legacy-service-account-token-cleaner
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: metrics-server
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: metrics-server
            app.kubernetes.io/version: 0.7.2
          name: metrics-server
          namespace: kube-system
      - metadata:
          name: namespace-controller
          namespace: kube-system
      - metadata:
          name: node-controller
          namespace: kube-system
      - metadata:
          name: persistent-volume-binder
          namespace: kube-system
      - metadata:
          name: pod-garbage-collector
          namespace: kube-system
      - metadata:
          name: pv-protection-controller
          namespace: kube-system
      - metadata:
          name: pvc-protection-controller
          namespace: kube-system
      - metadata:
          name: replicaset-controller
          namespace: kube-system
      - metadata:
          name: replication-controller
          namespace: kube-system
      - metadata:
          name: resourcequota-controller
          namespace: kube-system
      - metadata:
          name: root-ca-cert-publisher
          namespace: kube-system
      - metadata:
          name: service-account-controller
          namespace: kube-system
      - metadata:
          name: service-controller
          namespace: kube-system
      - metadata:
          name: statefulset-controller
          namespace: kube-system
      - metadata:
          name: tagging-controller
          namespace: kube-system
      - metadata:
          name: ttl-after-finished-controller
          namespace: kube-system
      - metadata:
          name: ttl-controller
          namespace: kube-system
      - metadata:
          name: validatingadmissionpolicy-status-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: rafay-system
      - metadata:
          labels:
            authz-expiry: "1766520131"
            authz-refreshed: "1766491331"
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: rs-45admin-64rafay-46co
          name: rs-45admin-64rafay-46co
          namespace: rafay-system
      - metadata:
          labels:
            app.kubernetes.io/managed-by: Helm
            k8smgmt.io/project: defaultproject
            rep-addon: v2-infra
            rep-cluster: empw4xk
            rep-cluster-name: rauto-eks-import-3276
            rep-drift-reconcillation: disabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: 28oozzm
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: lk5xw2e
          name: system-sa
          namespace: rafay-system
      serviceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-3276-cluster-ServiceRole-bw2oWEHNJCO2
      withOIDC: true
    managedNodeGroups:
    - amiFamily: Bottlerocket
      availabilityZones:
      - us-east-1a
      - us-east-1b
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-3276-nodeg-NodeInstanceRole-3525MaZVxSJM
      instanceType: t3.xlarge
      labels:
        alpha.eksctl.io/cluster-name: rauto-eks-import-3276
        alpha.eksctl.io/nodegroup-name: rocket-bottle-5
      maxSize: 2
      name: rocket-bottle-5
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-08675a95bf74b29ba
      subnets:
      - subnet-0f9ebe6e54cfece6f
      - subnet-0c9307954179e44b7
      tags:
        Name: eksctl-rauto-eks-import-3276-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-3276
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: rocket-bottle-5
        alpha.eksctl.io/nodegroup-type: managed
        build_num: qc-stage-new-k8s-version-121
        creation_time: "2025-12-23T11:40:50Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-3276
        email: automation@rafay.co
        env: automation
        squad: all
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: rauto-eks-import-3276
      region: us-east-1
      tags:
        Name: eksctl-rauto-eks-import-3276-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-3276
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.217.0
        build_num: qc-stage-new-k8s-version-121
        creation_time: "2025-12-23T11:40:50Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-3276
        email: automation@rafay.co
        env: automation
        squad: all
      version: "1.31"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      id: vpc-018763a2742403c1f
      securityGroup: sg-057ffc26f23cd3b06
      sharedNodeSecurityGroup: sg-08675a95bf74b29ba
      subnets:
        private:
          subnet-0c9307954179e44b7:
            id: subnet-0c9307954179e44b7
          subnet-0f9ebe6e54cfece6f:
            id: subnet-0f9ebe6e54cfece6f
        public:
          subnet-088d5c2c22dee4908:
            id: subnet-088d5c2c22dee4908
          subnet-08cad513fcf26d59a:
            id: subnet-08cad513fcf26d59a
  systemComponentsPlacement:
    daemonSetOverride:
      tolerations:
      - operator: Exists
    nodeSelector:
      key: rauto
    tolerations:
    - effect: NoSchedule
      key: nodetaint
      operator: Equal
      value: rauto
  type: aws-eks
