apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-356168377
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_370939968
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.21.1-eksbuild.1
    - name: coredns
      version: v1.12.4-eksbuild.1
    - name: kube-proxy
      version: v1.33.5-eksbuild.2
    addonsConfig: {}
    autoModeConfig: {}
    metadata:
      name: rauto-eks-356168377
      region: us-east-1
      tags:
        DeleteBefore: "2026-01-13T15:30:27Z"
        build_num: master-sanity-master-157
        creation_time: "2026-01-13T07:30:27Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1768289427"
        squad: blue
      version: "1.33"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      labels:
        k8smgmt.io/vm-operator: ""
      maxSize: 2
      minSize: 2
      name: rauto-ng-356168377
      privateNetworking: true
      version: "1.33"
      volumeSize: 80
      volumeType: gp2
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private:
          subnet-06114706579ea10c0:
            id: subnet-06114706579ea10c0
          subnet-0c93348944b797969:
            id: subnet-0c93348944b797969
        public:
          subnet-00afb1bd23c788794:
            id: subnet-00afb1bd23c788794
          subnet-097e192276767658d:
            id: subnet-097e192276767658d
  proxyConfig: {}
  type: aws-eks
