apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-awsrhel-594443126
  project: defaultproject
spec:
  blueprint:
    name: rauto-blueprint-open-594443126
    version: v1
  config:
    installerTtl: 365
    kubernetesVersion: v1.32.9
    network:
      cni:
        name: Cilium
        version: 1.14.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    platformVersion: v1.1.0
  type: mks
