apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: rauto-cli-aws-hacluster-146815619
  project: defaultproject
spec:
  blueprint:
    name: default-upstream
  config:
    autoApproveNodes: true
    highAvailability: true
    kubernetesVersion: v1.33.0
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-1-33
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.1.33
      roles:
      - Worker
      - ControlPlane
      - Storage
      ssh:
        ipAddress: 52.200.17.131
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-2-173
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.2.173
      roles:
      - Worker
      - ControlPlane
      - Storage
      ssh:
        ipAddress: 3.90.210.81
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-4-126
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.4.126
      roles:
      - Worker
      - ControlPlane
      - Storage
      ssh:
        ipAddress: 13.220.134.39
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
  type: mks
