apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-aws-flatcar-rook-910770749
  project: defaultproject
spec:
  blueprint:
    name: default-upstream
  config:
    installerTtl: 365
    kubernetesVersion: v1.34.1
    network:
      cni:
        name: Cilium
        version: 1.14.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: ip-172-31-8-188
      operatingSystem: Flatcar Container by Kinvolk4081.2.1
      privateIP: 172.31.8.188
      roles:
      - Worker
      - Storage
    - arch: x86_64
      hostname: ip-172-31-4-130
      operatingSystem: Flatcar Container by Kinvolk4081.2.1
      privateIP: 172.31.4.130
      roles:
      - Worker
      - Storage
    - arch: x86_64
      hostname: ip-172-31-3-250
      operatingSystem: Flatcar Container by Kinvolk4081.2.1
      privateIP: 172.31.3.250
      roles:
      - Worker
      - ControlPlane
      - Storage
    platformVersion: v1.1.0
  type: mks
