apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rautocdktf-eks-811507
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rautocdktf-cloudp-811507
  config:
    addons:
    - name: coredns
      version: latest
    - name: vpc-cni
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    cloudWatch: {}
    metadata:
      name: rautocdktf-eks-811507
      region: us-east-1
      tags:
        build_num: local
        email: automation@rafay.co
        env: automation
        squad: local
      version: "1.32"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: Ubuntu2204
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxSize: 2
      minSize: 1
      name: rauto-ng0
      privateNetworking: true
      version: "1.32"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
