apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rautocdktf-eks-674351
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rautocdktf-cloudp-674351
  config:
    accessConfig:
      authenticationMode: API
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: latest
    - name: vpc-cni
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-efs-csi-driver
      version: latest
    - name: snapshot-controller
      version: latest
    - name: amazon-cloudwatch-observability
      version: latest
    - name: aws-mountpoint-s3-csi-driver
      version: latest
    - name: adot
      version: latest
    - name: aws-guardduty-agent
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    cloudWatch: {}
    managedNodeGroups:
    - ami: ami-099af0196b2d0ff43
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxPodsPerNode: 0
      maxSize: 2
      minSize: 1
      name: rauto-ngmanaged0
      overrideBootstrapCommand: '[Bottlerocket]'
      privateNetworking: true
      spot: false
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    metadata:
      name: rautocdktf-eks-674351
      region: us-east-1
      tags:
        build_num: master-sanity-master-98
        email: automation@rafay.co
        env: automation
        squad: vikings
      version: "1.33"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
