apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    key1: value1
    key2: value2
  name: rauto-gke-92
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto-gke-cp-92
  config:
    controlPlaneVersion: "1.32"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-c
      defaultNodeLocations:
        enabled: true
        zones:
        - us-central1-c
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: phani-vpc1
      subnetName: sub1-phani-vpc1
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.32"
      size: 1
    - machineConfig:
        accelerators:
        - acceleratorSharing:
            maxSharedClients: 2
            strategy: TIME_SHARING
          count: 1
          gpuDriverInstallation:
            config:
              version: LATEST
            type: google-managed
          type: nvidia-tesla-t4
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: n1-standard-4
      name: gpu-nodepool
      nodeVersion: "1.32"
      size: 1
    - machineConfig:
        accelerators:
        - acceleratorSharing:
            maxSharedClients: 2
            strategy: TIME_SHARING
          count: 1
          gpuDriverInstallation:
            config: null
            type: user-managed
          type: nvidia-tesla-t4
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: n1-standard-4
      name: day-2-gpu-nodepool-464
      nodeVersion: "1.31"
      size: 1
    preBootstrapCommands:
    - ""
    - ""
  type: gke
