apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-hacluster-969400341
  project: defaultproject
spec:
  blueprint:
    name: default-upstream
  config:
    highAvailability: true
    installerTtl: 365
    kubernetesVersion: v1.34.1
    network:
      cni:
        name: Cilium
        version: 1.14.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-10-206
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.10.206
      roles:
      - Worker
      - Storage
    - arch: amd64
      hostname: ip-172-31-1-179
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.1.179
      roles:
      - Worker
    - arch: amd64
      hostname: ip-172-31-13-175
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.13.175
      roles:
      - Worker
      - ControlPlane
      - Storage
    - arch: amd64
      hostname: ip-172-31-14-134
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.14.134
      roles:
      - Worker
      - ControlPlane
      - Storage
    - arch: amd64
      hostname: ip-172-31-1-74
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.1.74
      roles:
      - Storage
      - Worker
      - ControlPlane
    - arch: amd64
      hostname: ip-172-31-3-57
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.3.57
      roles:
      - Worker
      - ControlPlane
      - Storage
    - arch: amd64
      hostname: ip-172-31-8-3
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.8.3
      roles:
      - Worker
      - ControlPlane
      - Storage
    platformVersion: v1.1.0
  proxy: {}
  type: mks
