apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-hacluster-160414681
  project: defaultproject
spec:
  blueprint:
    name: default-upstream
  config:
    highAvailability: true
    installerTtl: 365
    kubernetesVersion: v1.32.9
    network:
      cni:
        name: Cilium
        version: 1.14.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - roles:
      - Worker
    - roles:
      - Worker
    - roles:
      - Worker
    - roles:
      - Worker
    - roles:
      - Worker
    - roles:
      - Worker
    platformVersion: v1.1.0
  proxy: {}
  type: mks
