apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-cm-951350320
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_475956044
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEditPolicy
        kubernetesUsername: shobhit-rafay
        principalARN: arn:aws:iam::211125364662:user/shobhit@rafay.co
        type: STANDARD
      authenticationMode: API
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.21.1-eksbuild.1
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.32.9-eksbuild.2
    - name: aws-ebs-csi-driver
      version: latest
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    managedNodeGroups:
    - amiFamily: Bottlerocket
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng1-951350320
      overrideBootstrapCommand: null
      privateNetworking: true
      version: "1.33"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: Bottlerocket
      bottlerocket:
        settings:
          pki:
            my-trusted-bundle:
              data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdUakNDQlRhZ0F3SUJBZ0lUWUFBQUFDTi91dnZiMUNRbEhnQUFBQUFBSXpBTkJna3Foa2lHOXcwQkFRc0YKQURCZU1STXdFUVlLQ1pJbWlaUHlMR1FCR1JZRFkyOXRNUmN3RlFZS0NaSW1pWlB5TEdRQkdSWUhabUZqZEhObApkREVTTUJBR0NnbVNKb21UOGl4a0FSa1dBbkJqTVJvd0dBWURWUVFERXhGR1lXTjBVMlYwVUc5c2FXTjVNMEV3Ck1UQWVGdzB5TURBeE1EZ3hOVEV6TWpGYUZ3MHlOVEF4TURZeE5URXpNakZhTUYweEV6QVJCZ29Ka2lhSmsvSXMKWkFFWkZnTmpiMjB4RnpBVkJnb0praWFKay9Jc1pBRVpGZ2RtWVdOMGMyVjBNUkl3RUFZS0NaSW1pWlB5TEdRQgpHUllDY0dNeEdUQVhCZ05WQkFNVEVFWmhZM1JUWlhSSmMzTjFaVE5CTURFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEU0w4dFJJcnoxZlFhUVBINWZuUEVrbS9DcXNHRlRFajZXaVdYTmVrTmQKMjN1VHo1Qlk0bXJCOWJVdzVuMDZPRDIzTzJFbEV6NGtSUXVaK3FlSjBxVU11dlQ4bERZb3lnSnpkTElzSHFRNwpqSkxFZnkxUmx6V0NRbko1WThvWFVyUTMybmt4T1FiQUpQUC9YNFJLUFdrY2hJOThvVVQ4SXh0dlJNV2MxNThpCjVPZ0dXZ2V0NFc5dSt1UHFnSDk3bzFLMTEvMGFjY1h2SDl4eFZTZFFCdEdDeVVaT3EvRU14RFZrUlI2b0JnbUYKdVI5cUl4b0Jqd2U3TEcxTzROMHVDUS9jOFZRWkF3MFh3bURqTHBhbWtaUnpyK3laLzVlOHZWeE51c1gxcjlwagpwUERxb09XbTNKeWFjZDF2VFowUVBveGdHVENEaUROZmNJek9hRkRkNC9jZEFnTUJBQUdqZ2dNRU1JSURBREFRCkJna3JCZ0VFQVlJM0ZRRUVBd0lCQVRBakJna3JCZ0VFQVlJM0ZRSUVGZ1FVMkk0SnQrU2k0US9VZ01zWE1ZUVAKZ1FiSDZxVXdIUVlEVlIwT0JCWUVGRUpieWJFWDhFTGRCTEU1WWNFKzk3cDV2TEJtTUJrR0NTc0dBUVFCZ2pjVQpBZ1FNSGdvQVV3QjFBR0lBUXdCQk1Bc0dBMVVkRHdRRUF3SUJoakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjhHCkExVWRJd1FZTUJhQUZDamoySXVlclE4U216REovZVE4bGJNQXdMT1BNSUlCR2dZRFZSMGZCSUlCRVRDQ0FRMHcKZ2dFSm9JSUJCYUNDQVFHR2djVnNaR0Z3T2k4dkwwTk9QVVpoWTNSVFpYUlFiMnhwWTNrelFUQXhMRU5PUFZCTApTUzFRVDB4SlExa3pRVEF4TEVOT1BVTkVVQ3hEVGoxUWRXSnNhV01sTWpCTFpYa2xNakJUWlhKMmFXTmxjeXhEClRqMVRaWEoyYVdObGN5eERUajFEYjI1bWFXZDFjbUYwYVc5dUxFUkRQWEJqTEVSRFBXWmhZM1J6WlhRc1JFTTkKWTI5dFAyTmxjblJwWm1sallYUmxVbVYyYjJOaGRHbHZia3hwYzNRL1ltRnpaVDl2WW1wbFkzUkRiR0Z6Y3oxagpVa3hFYVhOMGNtbGlkWFJwYjI1UWIybHVkSVkzYUhSMGNEb3ZMM0JyYVM1bVlXTjBjMlYwTG1OdmJTOURaWEowClJXNXliMnhzTDBaaFkzUlRaWFJRYjJ4cFkza3pRVEF4TG1OeWJEQ0NBUzRHQ0NzR0FRVUZCd0VCQklJQklEQ0MKQVJ3d2diWUdDQ3NHQVFVRkJ6QUNob0dwYkdSaGNEb3ZMeTlEVGoxR1lXTjBVMlYwVUc5c2FXTjVNMEV3TVN4RApUajFCU1VFc1EwNDlVSFZpYkdsakpUSXdTMlY1SlRJd1UyVnlkbWxqWlhNc1EwNDlVMlZ5ZG1salpYTXNRMDQ5ClEyOXVabWxuZFhKaGRHbHZiaXhFUXoxd1l5eEVRejFtWVdOMGMyVjBMRVJEUFdOdmJUOWpRVU5sY25ScFptbGoKWVhSbFAySmhjMlUvYjJKcVpXTjBRMnhoYzNNOVkyVnlkR2xtYVdOaGRHbHZia0YxZEdodmNtbDBlVEJoQmdncgpCZ0VGQlFjd0FvWlZhSFIwY0RvdkwzQnJhUzVtWVdOMGMyVjBMbU52YlM5RFpYSjBSVzV5YjJ4c0wxQkxTUzFRClQweEpRMWt6UVRBeExuQmpMbVpoWTNSelpYUXVZMjl0WDBaaFkzUlRaWFJRYjJ4cFkza3pRVEF4TG1OeWREQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcjIzYmtTbWFQRlEzU1d4U1RocUdjaXNKbFRzTncxenJtWXFMZ1RBdApqUUVKakd2NkNneEE2MU9lS2J2RTZGU3BUY01CWUxFMlJicno3T2xNV1pJb2xMdzJtSytoOVJVUVNrNklJU04xCmJ1QXVJM0tkckVvdDNRbDNuM0krYlB4ODhnR3lxYXJwOHE2YmJHZmpwVzgzZ1dJckJrck9KM05xV2dlRTRTbW0KSU5IK1RBWjB0U29uQUx0K1p3bnVRZjU4ZTR4dnN5VitoZ0VJc2ZZRUlHQTFMOUZ3cHp2cWJQWDlVZVk3eGdsQQpibFJqUVY0ajJvZVB6b1RPZFBYeXI4Q3dIcHM1Y0NMbHA1WkpOV3haYm1Ed25iT2UwTm1waUoxVjRUbWVoRmlWCjU4VU40aFJjWTZEVTF1SHp2cjlaWjdkMUg1ckdWcW1KOUJCM3B5SGRwMW9Zc0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
              trusted: true
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng2-951350320
      overrideBootstrapCommand: null
      privateNetworking: true
      tags:
        key1: value2
        key2: value3
      version: "1.34"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: WindowsServer2019FullContainer
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-ng-win-39516755
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.33"
      volumeSize: 80
      volumeType: gp2
    metadata:
      name: rauto-cm-951350320
      region: us-east-1
      tags:
        DeleteBefore: "2026-01-13T19:18:08Z"
        build_num: master-sanity-master-158
        creation_time: "2026-01-13T11:18:08Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1768303088"
        squad: vikings
      version: "1.34"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
