apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rautocdktf-eks-666421
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rautocdktf-cloudp-666421
  config:
    addons:
    - name: coredns
      version: latest
    - name: vpc-cni
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    cloudWatch:
      clusterLogging:
        enableTypes:
        - audit
    iam:
      serviceAccounts:
      - metadata:
          name: rauto-test-sa
          namespace: rafay-system
        roleOnly: true
        wellKnownPolicies:
          autoScaler: false
          awsLoadBalancerController: true
          certManager: false
          ebsCSIController: false
          efsCSIController: false
          externalDNS: false
          imageBuilder: false
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxPodsPerNode: 0
      maxSize: 2
      minSize: 1
      name: rauto-ngmanaged0
      privateNetworking: true
      spot: false
      version: "1.31"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    metadata:
      name: rautocdktf-eks-666421
      region: us-east-1
      tags:
        build_num: master-sanity-master-98
        email: automation@rafay.co
        env: automation
        squad: vikings
      version: "1.31"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
