apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    rauto: rauto-terraform-aks-42180
  name: rauto-terraform-aks-42180
  project: defaultproject
spec:
  blueprintConfig:
    name: default-aks
    version: latest
  cloudCredentials: rauto_299913642
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-terraform-aks-42180
    spec:
      maintenanceConfigurations:
      - apiVersion: "2024-01-01"
        name: aksManagedAutoUpgradeSchedule
        properties:
          maintenanceWindow:
            durationHours: 5
            schedule:
              weekly:
                dayOfWeek: Friday
                intervalWeeks: 1
            startDate: "2024-08-14"
            startTime: "13:30"
            utcOffset: "+05:30"
        type: Microsoft.ContainerService/managedClusters/maintenanceConfigurations
      - apiVersion: "2024-01-01"
        name: aksManagedNodeOSUpgradeSchedule
        properties:
          maintenanceWindow:
            durationHours: 4
            schedule:
              weekly:
                dayOfWeek: Friday
                intervalWeeks: 1
            startDate: "2024-08-10"
            startTime: "15:00"
            utcOffset: "+05:30"
        type: Microsoft.ContainerService/managedClusters/maintenanceConfigurations
      managedCluster:
        additionalMetadata:
          oms_workspace_location: centralindia
        apiVersion: "2023-11-01"
        identity:
          type: UserAssigned
          userAssignedIdentities:
            ? /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-cluster-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-fnf-cluster-identity
            : {}
        location: centralindia
        properties:
          aadProfile:
            managed: true
          addonProfiles:
            azureKeyvaultSecretsProvider:
              config:
                enableSecretRotation: "true"
                rotationPollInterval: 2m
              enabled: true
            azurePolicy:
              enabled: false
            httpApplicationRouting:
              enabled: false
            omsAgent:
              config:
                logAnalyticsWorkspaceResourceID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/gautham-rg-ci/providers/Microsoft.OperationalInsights/workspaces/gautham-aco-law-1
              enabled: true
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
            privateDNSZone: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/gautham-rg-ci/providers/Microsoft.Network/privateDnsZones/gautham.private.centralindia.azmk8s.io
          autoScalerProfile:
            balance-similar-node-groups: "false"
            expander: random
            max-empty-bulk-delete: "10"
            max-graceful-termination-sec: "600"
            max-node-provision-time: 15m
            max-total-unready-percentage: "45"
            new-pod-scale-up-delay: 10s
            ok-total-unready-count: "3"
            scale-down-delay-after-add: 10m
            scale-down-delay-after-delete: 10s
            scale-down-delay-after-failure: 3m
            scale-down-unneeded-time: 10m
            scale-down-unready-time: 20m
            scale-down-utilization-threshold: "0.5"
            scan-interval: 10s
            skip-nodes-with-local-storage: "true"
            skip-nodes-with-system-pods: "true"
          autoUpgradeProfile:
            nodeOsUpgradeChannel: NodeImage
            upgradeChannel: patch
          disableLocalAccounts: false
          dnsPrefix: rauto-terraform-aks-42180
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.33.3
          linuxProfile:
            adminUsername: iamadmin
            ssh:
              publicKeys:
              - keyData: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDY1+Nou/+D/Bv+gkb5LEZ72Ct/KQtwVzV07pbMfSdl2EyVdcVEduMdbLHXzGk/26RJaPbCk4BG6jhvE9PKmgVPJqD+1Jv3VblSLmDvm2dYcTqyZJmGpcM9UO1QVZzuLO75XUGXR/XmVpV48OulD9EePfp9eo+WxAMKM6zyQ4fDOGgaEvmtYSs2BQ6achqIaz5qYiCSGFkc4ypQIbNZ3E3dugx3FP5ffLxn3sTBGMjfYYr5VZIviCGrUHXTbyUq7LK8v+Vse22cKsbldvqAzh31/2PFBZnPuDbi8r4fmaoisOwSw2gGTQPANazE6F8ntyLalDZ0F/UDFsmCMsfXWW3MxQaERaOE/kE2Qk7zPFqBoZqBIaZK5h6TFM5HPjMtwAzc05tp/4aHUiXWT7tsrlumwiFiVweAstTWNuq2F18Z3FDIfnEJxi1uebrT5Be/Q+JqY7qD1lQgKUwZfmTdTm9joReXjo9a+DLyCCldEgOkZuPwsgqvD1ReMmiogi0z8W9ZIB4hid9qMAvEa3PE61R6w6vfbcfe2L+ubhu/AEBX69r8OTizhOLrcnoGcfGwwzdPkTBc6HyqeknSbVhUP4zVa7+tVIhXdaq7U68RmkhoeUbOwGrYuGrpaqdq9gVnlqjL1Y4gvM1pYg8NobHms9859UYVWLmfJQnKWVgMBWa5sQ==
                  mvgautham@rafay.co
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: Standard
            networkPlugin: azure
            networkPluginMode: overlay
            networkPolicy: calico
            outboundType: userDefinedRouting
            podCidr: 10.244.0.0/16
            serviceCidr: 10.0.0.0/16
          nodeResourceGroup: rauto-terraform-aks-42180
          oidcIssuerProfile:
            enabled: true
          powerState:
            code: Running
          securityProfile:
            workloadIdentity:
              enabled: true
        sku:
          name: Base
          tier: Free
        tags:
          email: automation@rafay.co
          env: automation
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2023-11-01"
        location: centralindia
        name: pool1
        properties:
          availabilityZones:
          - "1"
          - "2"
          - "3"
          count: 3
          enableAutoScaling: true
          maxCount: 5
          maxPods: 30
          minCount: 1
          mode: System
          nodeLabels:
            node-type: pool1
          orchestratorVersion: 1.33.3
          osType: Linux
          tags:
            email: automation@rafay.co
            env: automation
          type: VirtualMachineScaleSets
          upgradeSettings:
            maxSurge: 40%
          vmSize: Standard_DS2_v2
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2023-11-01"
        location: centralindia
        name: pool2
        properties:
          availabilityZones:
          - "1"
          - "2"
          - "3"
          count: 2
          enableAutoScaling: true
          maxCount: 5
          maxPods: 30
          minCount: 1
          mode: System
          nodeLabels:
            node-type: pool2
          nodeTaints:
          - CriticalAddonsOnly=true:NoSchedule
          - key2=value2:PreferNoSchedule
          orchestratorVersion: 1.33.3
          osType: Linux
          tags:
            email: automation@rafay.co
            env: automation
          type: VirtualMachineScaleSets
          upgradeSettings:
            maxSurge: 40%
          vmSize: Standard_DS2_v2
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
  sharing:
    enabled: true
    projects:
    - name: rauto-project-42180
    - name: rauto-project-one-42180
  type: aks
