apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-cm-826764211
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: rauto_611310510
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.20.3-eksbuild.1
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.31.10-eksbuild.12
    - name: eks-pod-identity-agent
      version: latest
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    iam:
      serviceAccounts:
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-irsa
          labels:
            irsalabel: rauto-irsalabel
          name: rauto-irsa
          namespace: rafay-system
        tags:
          irsatag: rauto-irsatag
      withOIDC: true
    metadata:
      name: rauto-cm-826764211
      region: us-east-1
      tags:
        DeleteBefore: "2025-10-11T02:57:16Z"
        build_num: master-sanity-master-3
        creation_time: "2025-10-10T18:57:16Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1760122636"
        squad: vikings
      version: "1.31"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng1-826764211
      overrideBootstrapCommand: null
      privateNetworking: true
      version: "1.31"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng2-826764211
      overrideBootstrapCommand: null
      privateNetworking: true
      version: "1.31"
      volumeSize: 80
      volumeType: gp2
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
