apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-import-1742
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: rauto_363430501
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
    addons:
    - name: aws-ebs-csi-driver
      serviceAccountRoleARN: arn:aws:iam::211125364662:role/AmazonEKSTFEBSCSIRole-rauto_eks_underscore_TPn0
      tags:
        eks_addon: ebs-csi
        terraform: "true"
      version: v1.20.0-eksbuild.1
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1b
    - us-east-1a
    - us-east-1c
    iam:
      serviceAccounts:
      - metadata:
          name: default
          namespace: default
      - metadata:
          name: default
          namespace: kube-node-lease
      - metadata:
          name: default
          namespace: kube-public
      - metadata:
          name: attachdetach-controller
          namespace: kube-system
      - metadata:
          name: aws-cloud-provider
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: aws-vpc-cni
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: aws-node
            app.kubernetes.io/version: v1.20.4
            helm.sh/chart: aws-vpc-cni-1.20.4
            k8s-app: aws-node
          name: aws-node
          namespace: kube-system
      - metadata:
          name: certificate-controller
          namespace: kube-system
      - metadata:
          name: clusterrole-aggregation-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: coredns
            k8s-app: kube-dns
          name: coredns
          namespace: kube-system
      - metadata:
          name: cronjob-controller
          namespace: kube-system
      - metadata:
          name: daemon-set-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: kube-system
      - metadata:
          name: deployment-controller
          namespace: kube-system
      - metadata:
          name: disruption-controller
          namespace: kube-system
      - attachRoleARN: arn:aws:iam::211125364662:role/AmazonEKSTFEBSCSIRole-rauto_eks_underscore_TPn0
        metadata:
          labels:
            app.kubernetes.io/component: csi-driver
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: aws-ebs-csi-driver
            app.kubernetes.io/version: 1.20.0
          name: ebs-csi-controller-sa
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/component: csi-driver
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: aws-ebs-csi-driver
            app.kubernetes.io/version: 1.20.0
          name: ebs-csi-node-sa
          namespace: kube-system
      - metadata:
          name: endpoint-controller
          namespace: kube-system
      - metadata:
          name: endpointslice-controller
          namespace: kube-system
      - metadata:
          name: endpointslicemirroring-controller
          namespace: kube-system
      - metadata:
          name: ephemeral-volume-controller
          namespace: kube-system
      - metadata:
          name: expand-controller
          namespace: kube-system
      - metadata:
          name: generic-garbage-collector
          namespace: kube-system
      - metadata:
          name: horizontal-pod-autoscaler
          namespace: kube-system
      - metadata:
          name: job-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: kube-proxy
            k8s-app: kube-proxy
          name: kube-proxy
          namespace: kube-system
      - metadata:
          name: namespace-controller
          namespace: kube-system
      - metadata:
          name: node-controller
          namespace: kube-system
      - metadata:
          name: persistent-volume-binder
          namespace: kube-system
      - metadata:
          name: pod-garbage-collector
          namespace: kube-system
      - metadata:
          name: pv-protection-controller
          namespace: kube-system
      - metadata:
          name: pvc-protection-controller
          namespace: kube-system
      - metadata:
          name: replicaset-controller
          namespace: kube-system
      - metadata:
          name: replication-controller
          namespace: kube-system
      - metadata:
          name: resourcequota-controller
          namespace: kube-system
      - metadata:
          name: root-ca-cert-publisher
          namespace: kube-system
      - metadata:
          name: service-account-controller
          namespace: kube-system
      - metadata:
          name: service-controller
          namespace: kube-system
      - metadata:
          name: statefulset-controller
          namespace: kube-system
      - metadata:
          name: tagging-controller
          namespace: kube-system
      - metadata:
          name: ttl-after-finished-controller
          namespace: kube-system
      - metadata:
          name: ttl-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: rafay-system
      - metadata:
          labels:
            authz-expiry: "1763647258"
            authz-refreshed: "1763618458"
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: rs-45admin-64rafay-46co
          name: rs-45admin-64rafay-46co
          namespace: rafay-system
      - metadata:
          labels:
            app.kubernetes.io/managed-by: Helm
            k8smgmt.io/project: defaultproject
            rep-addon: v2-infra
            rep-cluster: dk666gk
            rep-cluster-name: rauto-import-1742
            rep-drift-reconcillation: disabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: g298g1k
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: lk5xw2e
          name: system-sa
          namespace: rafay-system
      serviceRoleARN: arn:aws:iam::211125364662:role/rauto_eks_underscore_TPn0-cluster-20251120054048649700000003
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1b
      - us-east-1a
      - us-east-1c
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/node-group-1-eks-node-group-20251120054048648700000001
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: node-group-1-20251120055242526800000017
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-03c4f3566bee39c6f
      subnets:
      - subnet-0a6bcfcfe4f505758
      - subnet-0ab05e93428d1fed0
      - subnet-04fa934a61c065bb1
      tags:
        Name: node-group-1
        email: automation@rafay.co
        env: automation
      volumeSize: 20
      volumeType: gp2
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1b
      - us-east-1a
      - us-east-1c
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/node-group-2-eks-node-group-20251120054048649400000002
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: node-group-2-20251120055242527200000019
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-03c4f3566bee39c6f
      subnets:
      - subnet-0a6bcfcfe4f505758
      - subnet-0ab05e93428d1fed0
      - subnet-04fa934a61c065bb1
      tags:
        Name: node-group-2
        email: automation@rafay.co
        env: automation
      volumeSize: 20
      volumeType: gp2
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-ng-129588850
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp2
    metadata:
      name: rauto_eks_underscore_TPn0
      region: us-east-1
      tags:
        alpha.rafay.io/cluster-name: rauto_eks_underscore_TPn0
        alpha.rafay.io/sanitized-cluster-name: rauto-eks-underscore-TPn0-dk666gk
      version: "1.28"
    network:
      cni:
        name: aws-cni
    secretsEncryption:
      keyARN: arn:aws:kms:us-east-1:211125364662:key/fd8ef292-2d6b-497e-a675-0f0f9031a1ed
    vpc:
      cidr: 10.0.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      id: vpc-0c1526515fe684db8
      securityGroup: sg-0fd6b64565925bd59
      sharedNodeSecurityGroup: sg-03c4f3566bee39c6f
      subnets:
        private:
          subnet-04fa934a61c065bb1:
            id: subnet-04fa934a61c065bb1
          subnet-0a6bcfcfe4f505758:
            id: subnet-0a6bcfcfe4f505758
          subnet-0ab05e93428d1fed0:
            id: subnet-0ab05e93428d1fed0
  type: aws-eks
