apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    labels: ""
  name: rauto-cli-ha-ocicluster-941144191
  project: defaultproject
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    highAvailability: true
    installerTtl: 365
    kubernetesVersion: v1.32.9
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    platformVersion: v1.1.0
  type: mks
