apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: rauto-cli-aws-hacluster-15719476
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    highAvailability: true
    kubeletConfigurationOverrides: |-
      maxPods: 600
      rotateCertificates: true
    kubeletExtraArgs:
      max-pods: "800"
    kubernetesVersion: v1.34.1
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-16-57
      kubeletConfigurationOverrides: 'maxPods: 400'
      kubeletExtraArgs:
        max-pods: "100"
      labels:
        app: infra
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.16.57
      roles:
      - Worker
      ssh:
        ipAddress: 18.215.254.198
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
      taints:
      - effect: NoSchedule
        key: app
        value: infra
    - arch: amd64
      hostname: ip-172-31-20-89
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.20.89
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 54.237.209.93
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-30-242
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.30.242
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 13.217.83.195
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-31-161
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.31.161
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 54.173.192.105
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-16-237
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.16.237
      roles:
      - Worker
      ssh:
        ipAddress: 54.81.225.79
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
  systemComponentsPlacement:
    nodeSelector:
      app: infra
    tolerations:
    - effect: NoSchedule
      key: app
      operator: Equal
      value: infra
  type: mks
