apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-cm-125686362
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_566111482
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.20.5-eksbuild.1
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.32.9-eksbuild.2
    - name: aws-ebs-csi-driver
      version: latest
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    managedNodeGroups:
    - amiFamily: WindowsServer2019CoreContainer
      desiredCapacity: 2
      instanceType: t3.medium
      maxSize: 2
      minSize: 0
      name: rauto-ng2-win-195477965
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp2
    metadata:
      name: rauto-cm-125686362
      region: us-east-1
      tags:
        DeleteBefore: "2025-11-27T07:07:27Z"
        build_num: master-sanity-master-98
        creation_time: "2025-11-26T23:07:27Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1764198447"
        squad: vikings
      version: "1.33"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng-125686362
      privateNetworking: true
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: WindowsServer2019FullContainer
      desiredCapacity: 2
      instanceType: t3.medium
      maxSize: 2
      minSize: 1
      name: rauto-ng1-win-163715010
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp2
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
