apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    rauto: rauto-aks-479992353
  name: rauto-aks-479992353
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-7293793
    version: v3
  cloudCredentials: rauto_482914238
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-aks-479992353
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: rauto-aks-479992353-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.33.5
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 3
          enableAutoScaling: true
          maxCount: 3
          maxPods: 40
          minCount: 3
          mode: System
          orchestratorVersion: 1.33.5
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  type: aks
