apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-import-7302
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: rauto_926447007
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEventPolicy
        kubernetesGroups:
        - eks:managed
        kubernetesUsername: arn:aws:sts::211125364662:assumed-role/AWSServiceRoleForAmazonEKS/{{SessionName}}
        principalARN: arn:aws:iam::211125364662:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
        type: STANDARD
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-nodegroup-NodeInstanceRole-1ou3hRWzonAE
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-nodegroup-NodeInstanceRole-n2hFiIIWHScR
        type: EC2_LINUX
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/automation-user@rafay.co
        principalARN: arn:aws:iam::211125364662:user/automation-user@rafay.co
        type: STANDARD
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.32.6-eksbuild.12
    - name: metrics-server
      version: v0.8.0-eksbuild.5
    - name: vpc-cni
      serviceAccountRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-addon-vpc-cni-Role1-vsCYfciqdzOh
      version: v1.20.5-eksbuild.1
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1d
    iam:
      serviceAccounts:
      - metadata:
          name: default
          namespace: default
      - metadata:
          name: default
          namespace: kube-node-lease
      - metadata:
          name: default
          namespace: kube-public
      - metadata:
          name: attachdetach-controller
          namespace: kube-system
      - metadata:
          name: aws-cloud-provider
          namespace: kube-system
      - attachRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-addon-vpc-cni-Role1-vsCYfciqdzOh
        metadata:
          labels:
            app.kubernetes.io/instance: aws-vpc-cni
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: aws-node
            app.kubernetes.io/version: v1.20.5
            helm.sh/chart: aws-vpc-cni-1.20.5
            k8s-app: aws-node
          name: aws-node
          namespace: kube-system
        tags:
          alpha.eksctl.io/addon-name: vpc-cni
          alpha.eksctl.io/cluster-name: rauto-import-7302
          alpha.eksctl.io/eksctl-version: 0.217.0
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-import-7302
      - metadata:
          name: certificate-controller
          namespace: kube-system
      - metadata:
          name: clusterrole-aggregation-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: coredns
            k8s-app: kube-dns
          name: coredns
          namespace: kube-system
      - metadata:
          name: cronjob-controller
          namespace: kube-system
      - metadata:
          name: daemon-set-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: kube-system
      - metadata:
          name: deployment-controller
          namespace: kube-system
      - metadata:
          name: disruption-controller
          namespace: kube-system
      - metadata:
          name: endpoint-controller
          namespace: kube-system
      - metadata:
          name: endpointslice-controller
          namespace: kube-system
      - metadata:
          name: endpointslicemirroring-controller
          namespace: kube-system
      - metadata:
          name: ephemeral-volume-controller
          namespace: kube-system
      - metadata:
          name: expand-controller
          namespace: kube-system
      - metadata:
          name: generic-garbage-collector
          namespace: kube-system
      - metadata:
          name: horizontal-pod-autoscaler
          namespace: kube-system
      - metadata:
          name: job-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: kube-proxy
            k8s-app: kube-proxy
          name: kube-proxy
          namespace: kube-system
      - metadata:
          name: legacy-service-account-token-cleaner
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: metrics-server
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: metrics-server
            app.kubernetes.io/version: 0.7.2
          name: metrics-server
          namespace: kube-system
      - metadata:
          name: namespace-controller
          namespace: kube-system
      - metadata:
          name: node-controller
          namespace: kube-system
      - metadata:
          name: persistent-volume-binder
          namespace: kube-system
      - metadata:
          name: pod-garbage-collector
          namespace: kube-system
      - metadata:
          name: pv-protection-controller
          namespace: kube-system
      - metadata:
          name: pvc-protection-controller
          namespace: kube-system
      - metadata:
          name: replicaset-controller
          namespace: kube-system
      - metadata:
          name: replication-controller
          namespace: kube-system
      - metadata:
          name: resourcequota-controller
          namespace: kube-system
      - metadata:
          name: root-ca-cert-publisher
          namespace: kube-system
      - metadata:
          name: service-account-controller
          namespace: kube-system
      - metadata:
          name: service-controller
          namespace: kube-system
      - metadata:
          name: statefulset-controller
          namespace: kube-system
      - metadata:
          name: tagging-controller
          namespace: kube-system
      - metadata:
          name: ttl-after-finished-controller
          namespace: kube-system
      - metadata:
          name: ttl-controller
          namespace: kube-system
      - metadata:
          name: validatingadmissionpolicy-status-controller
          namespace: kube-system
      - metadata:
          name: volumeattributesclass-protection-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: rafay-system
      - metadata:
          labels:
            authz-expiry: "1765289665"
            authz-refreshed: "1765260865"
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: rs-45admin-64rafay-46co
          name: rs-45admin-64rafay-46co
          namespace: rafay-system
      - metadata:
          labels:
            app.kubernetes.io/managed-by: Helm
          name: system-sa
          namespace: rafay-system
      serviceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-cluster-ServiceRole-9Mutw2MYnIof
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      - us-east-1d
      desiredCapacity: 3
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-nodegroup-NodeInstanceRole-n2hFiIIWHScR
      instanceType: t3.medium
      labels:
        alpha.eksctl.io/cluster-name: rauto-import-7302
        alpha.eksctl.io/nodegroup-name: ng-custom
      maxSize: 3
      minSize: 2
      name: ng-custom
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-085b8d321ba9675e5
      subnets:
      - subnet-0070bd0eda4f39cbd
      - subnet-027724edcdd1a934b
      tags:
        Name: eksctl-rauto-import-7302-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-import-7302
        alpha.eksctl.io/cluster-oidc-enabled: "true"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: ng-custom
        alpha.eksctl.io/nodegroup-type: managed
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-import-7302
        nodegroup: custom
      taints:
      - effect: NoSchedule
        key: dedicated
        value: "true"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      - us-east-1d
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-import-7302-nodegroup-NodeInstanceRole-1ou3hRWzonAE
      instanceType: t3.medium
      labels:
        alpha.eksctl.io/cluster-name: rauto-import-7302
        alpha.eksctl.io/nodegroup-name: ng-nontainted
      maxSize: 1
      minSize: 1
      name: ng-nontainted
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-085b8d321ba9675e5
      subnets:
      - subnet-0070bd0eda4f39cbd
      - subnet-027724edcdd1a934b
      tags:
        Name: eksctl-rauto-import-7302-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-import-7302
        alpha.eksctl.io/cluster-oidc-enabled: "true"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: ng-nontainted
        alpha.eksctl.io/nodegroup-type: managed
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-import-7302
        nodegroup: custom
      volumeSize: 80
      volumeType: gp3
    - ami: ami-01872345de812817d
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-mng-al2023-540716139
      overrideBootstrapCommand: '| [Ubuntu]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp2
    metadata:
      name: rauto-import-7302
      region: us-east-1
      tags:
        Name: eksctl-rauto-import-7302-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-import-7302
        alpha.eksctl.io/cluster-oidc-enabled: "true"
        alpha.eksctl.io/eksctl-version: 0.217.0
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-import-7302
      version: "1.32"
    network:
      cni:
        name: aws-cni
        params:
          customCniCrdSpec:
            us-east-1a:
            - securityGroups:
              - sg-085b8d321ba9675e5
              subnet: subnet-0f167a7872299e1f3
            us-east-1d:
            - securityGroups:
              - sg-085b8d321ba9675e5
              subnet: subnet-0c673cd0f12e283d9
    nodeGroups:
    - ami: ami-01872345de812817d
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-ng-al2023-119011574
      overrideBootstrapCommand: '| [Ubuntu]'
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp2
    vpc:
      cidr: 10.0.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      id: vpc-07eda741952e02472
      securityGroup: sg-0bae0a9e33d72be1f
      sharedNodeSecurityGroup: sg-085b8d321ba9675e5
      subnets:
        private:
          subnet-0070bd0eda4f39cbd:
            id: subnet-0070bd0eda4f39cbd
          subnet-027724edcdd1a934b:
            id: subnet-027724edcdd1a934b
        public:
          subnet-0bce93b43a5c5892a:
            id: subnet-0bce93b43a5c5892a
          subnet-0f7043d3d5f1797b9:
            id: subnet-0f7043d3d5f1797b9
  type: aws-eks
