apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-onprem-10344
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.33.5
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: rauto-sdk-1762902924-81704
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.178
      roles:
      - Worker
      - ControlPlane
      - Storage
    platformVersion: v1.1.0
  type: mks
