apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-cm-694791641
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_371388169
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.21.1-eksbuild.1
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.30.14-eksbuild.18
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    metadata:
      name: rauto-cm-694791641
      region: us-east-1
      tags:
        DeleteBefore: "2026-01-13T23:51:17Z"
        build_num: master-sanity-master-158
        creation_time: "2026-01-13T15:51:17Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1768319477"
        squad: vikings
      version: "1.30"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: Ubuntu2204
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng1-694791641
      overrideBootstrapCommand: null
      privateNetworking: true
      version: "1.30"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: Ubuntu2204
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng2-694791641
      overrideBootstrapCommand: null
      privateNetworking: true
      version: "1.30"
      volumeSize: 80
      volumeType: gp2
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
