apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    rauto: rauto-aks-807225267
  name: rauto-aks-807225267
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-2918932
    version: v3
  cloudCredentials: rauto_912561805
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-aks-807225267
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: rauto-aks-807225267-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.33.5
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 3
          enableAutoScaling: true
          maxCount: 3
          maxPods: 40
          minCount: 3
          mode: System
          orchestratorVersion: 1.33.5
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2024-01-01"
        name: rauto422
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          nodeLabels:
            rautokey: rauto-value
          nodeTaints:
          - key1=value1:PreferNoSchedule
          orchestratorVersion: 1.33.5
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  type: aks
