apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    rauto: "true"
  name: rauto-gke-2802
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto-gke-cp-2802
  config:
    controlPlaneVersion: "1.32"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        region: us-central1
        zone: us-central1-a
      type: regional
    network:
      access:
        config:
          controlPlaneIPRange: 172.16.0.224/28
          disableSNAT: true
          enableAccessControlPlaneExternalIP: true
          enableAccessControlPlaneGlobal: true
          enablePrivateNodes: true
          firewallRules:
          - action: ALLOW
            description: firewall rule
            destinationRanges:
            - 172.16.0.48/28
            direction: EGRESS
            name: firewall-1
            priority: 1555
            rules:
            - ports:
              - "22284"
              - "9447"
              protocol: tcp
          - action: ALLOW
            description: firewall rule
            destinationRanges:
            - 172.16.0.48/28
            direction: EGRESS
            name: firewall-2
            priority: 1555
            rules:
            - ports:
              - "22284"
              - "9447"
              protocol: tcp
          - action: ALLOW
            description: firewall rule
            direction: INGRESS
            name: firewall-3
            priority: 1555
            rules:
            - ports:
              - "22284"
              - "9447"
              protocol: tcp
            sourceRanges:
            - 172.16.0.48/28
        type: private
      dataPlaneV2: ADVANCED_DATAPATH
      enableDataPlaneV2Metrics: true
      enableDataPlaneV2Observability: true
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: phani-vpc1
      subnetName: sub1-phani-vpc1
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.31"
      size: 1
    - autoScaling:
        maxNodes: 1
        minNodes: 1
      machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: second-nodepool
      nodeVersion: "1.31"
      size: 2
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-medium
      name: rauto-ng-9179
      nodeVersion: "1.31"
      size: 1
    preBootstrapCommands:
    - ""
    - ""
  type: gke
