apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: rauto-cli-aws-hacluster-828800787
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    highAvailability: true
    kubeletConfigurationOverrides: |-
      maxPods: 600
      rotateCertificates: true
    kubeletExtraArgs:
      max-pods: "800"
    kubernetesVersion: v1.34.1
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-27-169
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.27.169
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 98.81.194.162
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-20-113
      kubeletExtraArgs:
        max-pods: "100"
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.20.113
      roles:
      - Worker
      ssh:
        ipAddress: 3.92.160.68
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-18-124
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.18.124
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 54.145.195.10
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-31-64
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.31.64
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 100.24.29.58
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-27-0
      kubeletConfigurationOverrides: 'maxPods: 400'
      kubeletExtraArgs:
        max-pods: "50"
      labels:
        app: infra
      operatingSystem: Ubuntu22.04
      privateIP: 172.31.27.0
      roles:
      - Worker
      ssh:
        ipAddress: 34.230.16.48
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
      taints:
      - effect: NoSchedule
        key: app
        value: infra
  systemComponentsPlacement:
    nodeSelector:
      app: infra
    tolerations:
    - effect: NoSchedule
      key: app
      operator: Equal
      value: infra
  type: mks
