apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-303174056
  project: defaultproject
spec:
  blueprintConfig:
    name: default
    version: latest
  cloudCredentials: rauto_618622453
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.20.4-eksbuild.3
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.31.13-eksbuild.2
    - configurationValues: '{"defaultStorageClass": {"enabled": true}}'
      name: aws-ebs-csi-driver
      version: latest
    addonsConfig: {}
    autoModeConfig: {}
    metadata:
      name: rauto-eks-303174056
      region: us-east-1
      tags:
        DeleteBefore: "2025-11-20T21:30:26Z"
        build_num: master-sanity-master-96
        creation_time: "2025-11-20T13:30:26Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1763645426"
        squad: blue
      version: "1.31"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      labels:
        k8smgmt.io/vm-operator: ""
      maxSize: 2
      minSize: 2
      name: rauto-ng-303174056
      privateNetworking: true
      version: "1.31"
      volumeSize: 80
      volumeType: gp2
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private:
          subnet-06114706579ea10c0:
            id: subnet-06114706579ea10c0
          subnet-0c93348944b797969:
            id: subnet-0c93348944b797969
        public:
          subnet-00afb1bd23c788794:
            id: subnet-00afb1bd23c788794
          subnet-097e192276767658d:
            id: subnet-097e192276767658d
  proxyConfig: {}
  type: aws-eks
