apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-import-936
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-6901755
    version: v1
  cloudCredentials: rauto_786697772
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterInsightsPolicy
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEventPolicy
        kubernetesGroups:
        - eks:managed
        kubernetesUsername: arn:aws:sts::211125364662:assumed-role/AWSServiceRoleForAmazonEKS/{{SessionName}}
        principalARN: arn:aws:iam::211125364662:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
        type: STANDARD
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-936-nodegr-NodeInstanceRole-WZ2zgjYMy02P
        tags:
          Name: eksctl-rauto-eks-import-936-nodegroup-ng2/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-936
          alpha.eksctl.io/eksctl-version: 0.207.0-dev+87e1d6e6e.2025-04-03T01:12:37Z
          alpha.eksctl.io/nodegroup-name: ng2
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-936-nodegroup-ng2/464eef10-ba55-11f0-9231-12f02aa4c4e1
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-936-nodegroup-ng2
          build_num: local
          creation_time: "2025-11-05T14:27:40Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-936
          eksctl.io/v1alpha2/nodegroup-name: ng2
          email: automation@rafay.co
          env: automation
          squad: local
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-936-nodegr-NodeInstanceRole-dlnYfR28mbte
        tags:
          Name: eksctl-rauto-eks-import-936-nodegroup-ng1/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-936
          alpha.eksctl.io/eksctl-version: 0.207.0-dev+87e1d6e6e.2025-04-03T01:12:37Z
          alpha.eksctl.io/nodegroup-name: ng1
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-936-nodegroup-ng1/46a17be0-ba55-11f0-8fbc-0ed0135cae3f
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-936-nodegroup-ng1
          build_num: local
          creation_time: "2025-11-05T14:27:40Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-936
          eksctl.io/v1alpha2/nodegroup-name: ng1
          email: automation@rafay.co
          env: automation
          squad: local
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        - eks:kube-proxy-windows
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-936-nodegr-NodeInstanceRole-g6Sm8kCRxDZN
        tags:
          Name: eksctl-rauto-eks-import-936-nodegroup-eks-win-ngrauto/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-936
          alpha.eksctl.io/eksctl-version: 0.207.0-dev+87e1d6e6e.2025-04-03T01:12:37Z
          alpha.eksctl.io/nodegroup-name: eks-win-ngrauto
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-936-nodegroup-eks-win-ngrauto/46a0dfa0-ba55-11f0-871f-12d173d1fd29
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-936-nodegroup-eks-win-ngrauto
          build_num: local
          creation_time: "2025-11-05T14:27:40Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-936
          eksctl.io/v1alpha2/nodegroup-name: eks-win-ngrauto
          email: automation@rafay.co
          env: automation
          squad: local
        type: EC2_WINDOWS
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-936-nodegr-NodeInstanceRole-qeFXniLCW3AX
        type: EC2_LINUX
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/automation-user@rafay.co
        principalARN: arn:aws:iam::211125364662:user/automation-user@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: rautouser
        principalARN: arn:aws:iam::211125364662:user/kalyan@rafay.co
        tags:
          Name: eksctl-rauto-eks-import-936-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-936
          alpha.eksctl.io/eksctl-version: 0.207.0-dev+87e1d6e6e.2025-04-03T01:12:37Z
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-936-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V/e458f620-ba54-11f0-bdf8-0affdaba53c5
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-936-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V
          build_num: local
          creation_time: "2025-11-05T14:27:40Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-936
          email: automation@rafay.co
          env: automation
          squad: local
        type: STANDARD
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: v1.11.3-eksbuild.1
    - name: kube-proxy
      version: v1.31.10-eksbuild.12
    - name: metrics-server
      version: v0.8.0-eksbuild.2
    - name: vpc-cni
      version: v1.20.4-eksbuild.1
    - name: aws-ebs-csi-driver
      version: v1.51.1-eksbuild.1
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    iam:
      serviceAccounts:
      - metadata:
          name: default
          namespace: default
      - metadata:
          name: default
          namespace: default-rafay-master-sanity-automation
      - metadata:
          name: default
          namespace: kube-node-lease
      - metadata:
          name: default
          namespace: kube-public
      - metadata:
          name: attachdetach-controller
          namespace: kube-system
      - metadata:
          name: aws-cloud-provider
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: aws-vpc-cni
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: aws-node
            app.kubernetes.io/version: v1.20.4
            helm.sh/chart: aws-vpc-cni-1.20.4
            k8s-app: aws-node
          name: aws-node
          namespace: kube-system
      - metadata:
          name: certificate-controller
          namespace: kube-system
      - metadata:
          name: clusterrole-aggregation-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: coredns
            k8s-app: kube-dns
          name: coredns
          namespace: kube-system
      - metadata:
          name: cronjob-controller
          namespace: kube-system
      - metadata:
          name: daemon-set-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: kube-system
      - metadata:
          name: deployment-controller
          namespace: kube-system
      - metadata:
          name: disruption-controller
          namespace: kube-system
      - metadata:
          name: endpoint-controller
          namespace: kube-system
      - metadata:
          name: endpointslice-controller
          namespace: kube-system
      - metadata:
          name: endpointslicemirroring-controller
          namespace: kube-system
      - metadata:
          name: ephemeral-volume-controller
          namespace: kube-system
      - metadata:
          name: expand-controller
          namespace: kube-system
      - metadata:
          name: generic-garbage-collector
          namespace: kube-system
      - metadata:
          name: horizontal-pod-autoscaler
          namespace: kube-system
      - metadata:
          name: job-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: kube-proxy
            k8s-app: kube-proxy
          name: kube-proxy
          namespace: kube-system
      - metadata:
          name: legacy-service-account-token-cleaner
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: metrics-server
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: metrics-server
            app.kubernetes.io/version: 0.7.2
          name: metrics-server
          namespace: kube-system
      - metadata:
          name: namespace-controller
          namespace: kube-system
      - metadata:
          name: node-controller
          namespace: kube-system
      - metadata:
          name: persistent-volume-binder
          namespace: kube-system
      - metadata:
          name: pod-garbage-collector
          namespace: kube-system
      - metadata:
          name: pv-protection-controller
          namespace: kube-system
      - metadata:
          name: pvc-protection-controller
          namespace: kube-system
      - metadata:
          name: replicaset-controller
          namespace: kube-system
      - metadata:
          name: replication-controller
          namespace: kube-system
      - metadata:
          name: resourcequota-controller
          namespace: kube-system
      - metadata:
          name: root-ca-cert-publisher
          namespace: kube-system
      - metadata:
          name: service-account-controller
          namespace: kube-system
      - metadata:
          name: service-controller
          namespace: kube-system
      - metadata:
          name: statefulset-controller
          namespace: kube-system
      - metadata:
          name: tagging-controller
          namespace: kube-system
      - metadata:
          name: ttl-after-finished-controller
          namespace: kube-system
      - metadata:
          name: ttl-controller
          namespace: kube-system
      - metadata:
          name: validatingadmissionpolicy-status-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: rafay-system
      - metadata:
          labels:
            authz-expiry: "1762383025"
            authz-refreshed: "1762354225"
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: rs-45admin-64rafay-46co
          name: rs-45admin-64rafay-46co
          namespace: rafay-system
      - metadata:
          annotations:
            kubectl.kubernetes.io/last-applied-configuration: |
              {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"meta.helm.sh/release-name":"v2-infra","meta.helm.sh/release-namespace":"rafay-system"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"system-sa","namespace":"rafay-system"}}
            meta.helm.sh/release-name: v2-infra
            meta.helm.sh/release-namespace: rafay-system
            rafay.dev/original: '{"kind":"ServiceAccount","metadata":{"name":"system-sa","labels":{"app.kubernetes.io/managed-by":"Helm","rep-drift-reconcillation":"enabled"},"namespace":"rafay-system","annotations":{"meta.helm.sh/release-name":"v2-infra","meta.helm.sh/release-namespace":"rafay-system","rep-drift-action":"deny","rafay.dev/random":"NojcEgxPHV"}},"apiVersion":"v1"}'
            rafay.dev/ownerRef: '{"apiVersion":"cluster.rafay.dev/v2","kind":"Namespace","name":"rafay-system","uid":"8821e580-3a01-4a9f-812c-1f3872bb1fab","controller":true,"blockOwnerDeletion":true}'
            rafay.dev/random: NojcEgxPHV
            rep-drift-action: deny
          labels:
            app.kubernetes.io/managed-by: Helm
            k8smgmt.io/project: defaultproject
            rep-addon: v2-infra
            rep-cluster: d2wnx82
            rep-cluster-name: rauto-eks-import-936
            rep-drift-reconcillation: disabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: emp84xk
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: lk5xw2e
          name: system-sa
          namespace: rafay-system
      serviceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-936-cluster-ServiceRole-qpfQEA2BHFC7
      withOIDC: true
    managedNodeGroups:
    - amiFamily: Bottlerocket
      availabilityZones:
      - us-east-1a
      - us-east-1b
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-936-nodegr-NodeInstanceRole-qeFXniLCW3AX
      instanceType: t3.xlarge
      labels:
        alpha.eksctl.io/cluster-name: rauto-eks-import-936
        alpha.eksctl.io/nodegroup-name: rocket-bottle-5
      maxSize: 2
      name: rocket-bottle-5
      privateNetworking: true
      securityGroups:
        attachIDs:
        - sg-0502a51f6056d1ced
      subnets:
      - subnet-095938faaa398db6b
      - subnet-05fa52de3a5f8bf51
      tags:
        Name: eksctl-rauto-eks-import-936-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-936
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.207.0-dev+87e1d6e6e.2025-04-03T01:12:37Z
        alpha.eksctl.io/nodegroup-name: rocket-bottle-5
        alpha.eksctl.io/nodegroup-type: managed
        build_num: local
        creation_time: "2025-11-05T14:27:40Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-936
        email: automation@rafay.co
        env: automation
        squad: local
      version: "1.32"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: rauto-eks-import-936
      region: us-east-1
      tags:
        Name: eksctl-rauto-eks-import-936-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-936
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.207.0-dev+87e1d6e6e.2025-04-03T01:12:37Z
        build_num: local
        creation_time: "2025-11-05T14:27:40Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-936
        email: automation@rafay.co
        env: automation
        squad: local
      version: "1.32"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-ng-863061192
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: WindowsServer2019CoreContainer
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-ng-904992473
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: WindowsServer2019FullContainer
      desiredCapacity: 1
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: rauto-ng-482853402
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      id: vpc-04659ad8e3afee848
      securityGroup: sg-0f16f5b5a229100eb
      sharedNodeSecurityGroup: sg-0502a51f6056d1ced
      subnets:
        private:
          subnet-05fa52de3a5f8bf51:
            id: subnet-05fa52de3a5f8bf51
          subnet-095938faaa398db6b:
            id: subnet-095938faaa398db6b
        public:
          subnet-06dbc9cc5f126e213:
            id: subnet-06dbc9cc5f126e213
          subnet-030f897a4fa4d9f44:
            id: subnet-030f897a4fa4d9f44
  systemComponentsPlacement:
    daemonSetOverride:
      tolerations:
      - operator: Exists
    nodeSelector:
      key: rauto
    tolerations:
    - effect: NoSchedule
      key: nodetaint
      operator: Equal
      value: rauto
  type: aws-eks
