apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-mks-terraform-144026664
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  config:
    autoApproveNodes: true
    highAvailability: true
    installerTtl: 365
    kubernetesVersion: v1.32.9
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: rauto-sdk-1764408676-167811
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.32
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.146.203.80
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764408746-630542
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.166
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.153.93.140
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764408816-955806
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.48
      roles:
      - Worker
      ssh:
        ipAddress: 132.226.155.163
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764408879-370848
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.236
      roles:
      - Worker
      ssh:
        ipAddress: 141.148.139.208
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764408613-820687
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.245
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.153.103.201
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    ssh:
      port: "22"
      privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
      username: ubuntu
  type: mks
