apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-cm-720346221
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: rauto_293549739
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSAdminPolicy
        kubernetesUsername: automationuser
        principalARN: arn:aws:iam::211125364662:user/kalyan@rafay.co
        type: STANDARD
      authenticationMode: API
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.32.9-eksbuild.2
    addonsConfig:
      autoApplyPodIdentityAssociations: true
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    managedNodeGroups:
    - amiFamily: Ubuntu2204
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng1-720346221
      overrideBootstrapCommand: null
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: Ubuntu2204
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng2-720346221
      overrideBootstrapCommand: null
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    metadata:
      name: rauto-cm-720346221
      region: us-east-1
      tags:
        DeleteBefore: "2025-12-15T16:51:00Z"
        build_num: local
        creation_time: "2025-12-15T08:51:00Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1765788660"
        squad: local
      version: "1.32"
    network:
      cni:
        name: Calico-v3.24.5
    secretsEncryption:
      keyARN: arn:aws:kms:us-east-1:211125364662:key/d30cd169-de6e-43e5-9f06-0a8eab64c2d8
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
