apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-368500313
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-spc-blueprint-591616368
    version: v1
  cloudCredentials: rauto_758107154
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.20.5-eksbuild.1
    - name: coredns
      version: v1.11.4-eksbuild.24
    - name: kube-proxy
      version: v1.31.13-eksbuild.2
    - name: aws-ebs-csi-driver
      version: latest
    addonsConfig: {}
    autoModeConfig: {}
    iam:
      serviceAccounts:
      - attachPolicy:
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
            - arn:aws:secretsmanager:us-east-1:211125364662:secret:rauto-secrets-manager-QURCVI
          Version: "2012-10-17"
        metadata:
          name: rauto-sa-wk-spc-591616368
          namespace: rauto-ns-wk-spc-591616368
      withOIDC: true
    metadata:
      name: rauto-eks-368500313
      region: us-east-1
      tags:
        DeleteBefore: "2025-12-11T17:31:05Z"
        build_num: master-sanity-master-133
        creation_time: "2025-12-11T09:31:05Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1765445465"
        squad: green
      version: "1.31"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-ng-368500313
      privateNetworking: true
      version: "1.31"
      volumeSize: 80
      volumeType: gp2
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private:
          subnet-06114706579ea10c0:
            id: subnet-06114706579ea10c0
          subnet-0c93348944b797969:
            id: subnet-0c93348944b797969
        public:
          subnet-00afb1bd23c788794:
            id: subnet-00afb1bd23c788794
          subnet-097e192276767658d:
            id: subnet-097e192276767658d
  proxyConfig: {}
  type: aws-eks
