apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-aks-889376869
  project: defaultproject
spec:
  blueprintConfig:
    name: default-aks
  cloudCredentials: rauto_443601122
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-aks-889376869
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          aadProfile:
            adminGroupObjectIds:
            - 9063e71a-fc36-4281-ac4b-be26189fa004
            managed: true
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: true
          dnsPrefix: rauto-aks-889376869-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.33.0
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          orchestratorVersion: 1.33.0
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  type: aks
