apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-aks-628076818
  project: defaultproject
spec:
  blueprintConfig:
    name: rauto-blueprint-2175714
    version: v1
  cloudCredentials: rauto_809219617
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-aks-628076818
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: rauto-aks-628076818-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.33.2
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: standard
            networkPlugin: azure
            networkPluginMode: overlay
            podCidr: 10.244.0.0/16
            serviceCidr: 10.0.0.0/16
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          orchestratorVersion: 1.33.2
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/qa-automation/providers/Microsoft.Network/virtualNetworks/rautoqa/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  type: aks
