apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-terraform-eks-295084242
  project: defaultproject
spec:
  blueprintConfig:
    name: custom-bp-eks-49025753
    version: v1
  cloudCredentials: rauto_825887001
  config:
    addons:
    - attachPolicy:
        Statement:
        - Condition:
            StringEquals:
              aws:username: kalyan
          Effect: Allow
          NotAction:
          - ec2:Describe*
          Resource: '*'
        Version: "2012-10-17"
      name: kube-proxy
      version: latest
    - attachPolicy:
        Statement:
        - Action:
          - ec2:AssignPrivateIpAddresses
          - ec2:AttachNetworkInterface
          - ec2:CreateNetworkInterface
          - ec2:DeleteNetworkInterface
          - ec2:DescribeInstances
          - ec2:DescribeTags
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribeInstanceTypes
          - ec2:DescribeSubnets
          - ec2:DetachNetworkInterface
          - ec2:ModifyNetworkInterfaceAttribute
          - ec2:UnassignPrivateIpAddresses
          Effect: Allow
          Resource: '*'
          Sid: AmazonEKSCNIPolicy
        - Action:
          - ec2:CreateTags
          Effect: Allow
          Resource:
          - arn:aws:ec2:*:*:network-interface/*
          Sid: AmazonEKSCNIPolicyENITag
        Version: "2012-10-17"
      name: vpc-cni
      version: latest
    - attachPolicy:
        Statement:
        - Action:
          - ec2:CreateSnapshot
          - ec2:AttachVolume
          - ec2:DetachVolume
          - ec2:ModifyVolume
          - ec2:DescribeAvailabilityZones
          - ec2:DescribeInstances
          - ec2:DescribeSnapshots
          - ec2:DescribeTags
          - ec2:DescribeVolumes
          - ec2:DescribeVolumesModifications
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:CreateTags
          Condition:
            StringEquals:
              ec2:CreateAction:
              - CreateVolume
              - CreateSnapshot
          Effect: Allow
          Resource:
          - arn:aws:ec2:*:*:volume/*
          - arn:aws:ec2:*:*:snapshot/*
        - Action:
          - ec2:DeleteTags
          Effect: Allow
          Resource:
          - arn:aws:ec2:*:*:volume/*
          - arn:aws:ec2:*:*:snapshot/*
        - Action:
          - ec2:CreateVolume
          Condition:
            StringLike:
              aws:RequestTag/ebs.csi.aws.com/cluster: "true"
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:CreateVolume
          Condition:
            StringLike:
              aws:RequestTag/CSIVolumeName: '*'
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:DeleteVolume
          Condition:
            StringLike:
              ec2:ResourceTag/ebs.csi.aws.com/cluster: "true"
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:DeleteVolume
          Condition:
            StringLike:
              ec2:ResourceTag/CSIVolumeName: '*'
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:DeleteVolume
          Condition:
            StringLike:
              ec2:ResourceTag/kubernetes.io/created-for/pvc/name: '*'
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:DeleteSnapshot
          Condition:
            StringLike:
              ec2:ResourceTag/CSIVolumeSnapshotName: '*'
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:DeleteSnapshot
          Condition:
            StringLike:
              ec2:ResourceTag/ebs.csi.aws.com/cluster: "true"
          Effect: Allow
          Resource: '*'
        Version: "2012-10-17"
      name: aws-ebs-csi-driver
      version: latest
    - attachPolicy:
        Statement:
        - Action: ec2:Describe*
          Condition:
            StringEquals:
              aws:username: automation-user
          Effect: Allow
          Resource: '*'
        Version: "2012-10-17"
      name: coredns
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    metadata:
      name: rauto-terraform-eks-295084242
      region: us-east-1
      tags:
        build_num: master-sanity-master-98
        email: automation@rafay.co
        env: automation
        squad: vikings
      version: "1.28"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 1
      name: ng1
      privateNetworking: true
      version: "1.28"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    secretsEncryption: {}
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
