apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-ocicluster-546622409
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    installerTtl: 365
    kubernetesVersion: v1.32.9
    network:
      cni:
        name: Canal
        version: Calico-3.27.3-Flannel-0.25.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: rauto-sdk-1764658159-425519
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.157
      roles:
      - Worker
    - arch: amd64
      hostname: rauto-sdk-1764658088-814398
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.146
      roles:
      - Worker
      - Storage
    - arch: amd64
      hostname: rauto-sdk-1764658026-265726
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.111
      roles:
      - Worker
      - ControlPlane
      - Storage
    platformVersion: v1.1.0
  type: mks
