apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-awsrhel10rook-328178360
  project: defaultproject
spec:
  blueprint:
    name: default-upstream
  config:
    installerTtl: 365
    kubernetesVersion: v1.33.5
    network:
      cni:
        name: Cilium
        version: 1.14.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    platformVersion: v1.1.0
  type: mks
