apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: rauto-cli-aws-hacluster-808803364
  project: defaultproject
spec:
  blueprint:
    name: default-upstream
  config:
    autoApproveNodes: true
    highAvailability: true
    kubernetesVersion: v1.31.8
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-4-202
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.4.202
      roles:
      - Worker
      - ControlPlane
      - Storage
      ssh:
        ipAddress: 18.209.5.127
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-13-218
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.13.218
      roles:
      - Worker
      - ControlPlane
      - Storage
      ssh:
        ipAddress: 13.220.48.221
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-15-192
      operatingSystem: Ubuntu24.04
      privateIP: 172.31.15.192
      roles:
      - Worker
      - ControlPlane
      - Storage
      ssh:
        ipAddress: 54.227.70.118
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/awstest.pem
        username: ubuntu
  type: mks
