apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rautocdktf-aks-862122
  project: defaultproject
spec:
  blueprintConfig:
    name: rautocdktf-blueprint-862122
    version: v2.0
  cloudCredentials: rautocdktf-cloudp-862122
  config:
    kind: aksClusterConfig
    metadata:
      name: rautocdktf-aks-862122
    spec:
      managedCluster:
        apiVersion: "2023-11-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          addonProfiles:
            azurePolicy:
              enabled: true
          disableLocalAccounts: false
          dnsPrefix: rautocdktf-aks-862122
          enablePodSecurityPolicy: false
          kubernetesVersion: 1.33.5
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: Standard
            networkPlugin: azure
            networkPluginMode: overlay
            podCidr: 192.168.0.0/16
            serviceCidr: 10.0.0.0/16
          nodeResourceGroup: qa-automation-node-862122
          powerState:
            code: Running
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2023-11-01"
        location: centralindia
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 1
          mode: System
          orchestratorVersion: 1.33.4
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  sharing:
    projects:
    - name: rautocdktf-project-862122
  type: aks
