apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eaas-eks-759872
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: rauto-eaas-projecttag-credentials-759872
  config:
    addons:
    - name: coredns
      version: latest
    - name: vpc-cni
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    iam:
      serviceAccounts:
      - attachPolicy:
          Statement:
          - Action: ec2:Describe*
            Effect: Allow
            Resource: '*'
          - Action: ec2:AttachVolume
            Effect: Allow
            Resource: '*'
          - Action: ec2:DetachVolume
            Effect: Allow
            Resource: '*'
          - Action:
            - elasticloadbalancing:*
            Effect: Allow
            Resource:
            - '*'
          Version: "2012-10-17"
        metadata:
          name: test-irsa
          namespace: yaml1
        roleOnly: false
      withOIDC: true
    metadata:
      name: rauto-eaas-eks-759872
      region: us-east-1
      tags:
        email: automation@rafay.co
        env: dev
      version: "1.32"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.medium
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 1
      minSize: 1
      name: ng-1
      privateNetworking: true
      tags:
        email: automation@rafay.co
        env: dev
      version: "1.32"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  type: aws-eks
