apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-728521932
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_289835410
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.20.3-eksbuild.1
    - name: coredns
      version: v1.11.4-eksbuild.22
    - name: kube-proxy
      version: v1.32.6-eksbuild.12
    addonsConfig: {}
    autoModeConfig: {}
    metadata:
      name: rauto-eks-728521932
      region: us-east-1
      tags:
        DeleteBefore: "2025-10-01T01:21:49Z"
        build_num: master-sanity-mini-sanity-pipeline-93
        creation_time: "2025-09-30T17:21:49Z"
        email: automation@rafay.co
        env: automation
        rauto_launch_timestamp: "1759252909"
        squad: blue
      version: "1.32"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      labels:
        k8smgmt.io/vm-operator: ""
      maxSize: 2
      minSize: 2
      name: rauto-ng-728521932
      privateNetworking: true
      version: "1.32"
      volumeSize: 80
      volumeType: gp2
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private:
          subnet-06114706579ea10c0:
            id: subnet-06114706579ea10c0
          subnet-0c93348944b797969:
            id: subnet-0c93348944b797969
        public:
          subnet-00afb1bd23c788794:
            id: subnet-00afb1bd23c788794
          subnet-097e192276767658d:
            id: subnet-097e192276767658d
  proxyConfig: {}
  type: aws-eks
