apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-gke-625
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto-gke-cp-625
  config:
    controlPlaneVersion: "1.31"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-a
      type: zonal
    network:
      access:
        config: null
        type: public
      dataPlaneV2: ADVANCED_DATAPATH
      enableDataPlaneV2Metrics: true
      enableDataPlaneV2Observability: true
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-2
      name: phani-default-nodepool
      nodeVersion: "1.31"
      size: 1
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-medium
      name: rauto-np-2338
      nodeVersion: "1.31"
      size: 2
    preBootstrapCommands:
    - ""
    - ""
    security:
      issueClientCertificate: true
  type: gke
