apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: rauto-cli-nonha-ocicluster-906205974
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    dedicatedControlPlane: true
    highAvailability: true
    kubernetesVersion: v1.32.9
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: rauto-sdk-1764416545-686203
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.111
      roles:
      - ControlPlane
      ssh:
        ipAddress: 129.153.214.230
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764416617-260755
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.216
      roles:
      - ControlPlane
      ssh:
        ipAddress: 129.146.125.190
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764416680-126192
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.131
      roles:
      - ControlPlane
      ssh:
        ipAddress: 144.24.18.155
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
    - arch: amd64
      hostname: rauto-sdk-1764416750-189053
      labels:
        key: rauto
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.225
      roles:
      - Worker
      ssh:
        ipAddress: 152.70.145.159
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
      taints:
      - effect: NoSchedule
        key: nodetaint
        value: rauto
    - arch: amd64
      hostname: rauto-sdk-1764416820-215948
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.42
      roles:
      - Worker
      ssh:
        ipAddress: 144.24.6.9
        port: "22"
        privateKeyPath: /home/ubuntu/rauto/rafay_keywords/api_common/../../rauto-config/infra_config/oci_key
        username: ubuntu
  type: mks
