apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-import-4125
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: rauto_600298249
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterInsightsPolicy
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEventPolicy
        kubernetesGroups:
        - eks:managed
        kubernetesUsername: arn:aws:sts::211125364662:assumed-role/AWSServiceRoleForAmazonEKS/{{SessionName}}
        principalARN: arn:aws:iam::211125364662:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
        type: STANDARD
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-nodeg-NodeInstanceRole-9YHcDwReWUTh
        tags:
          Name: eksctl-rauto-eks-import-4125-nodegroup-ng2/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-4125
          alpha.eksctl.io/eksctl-version: 0.217.0
          alpha.eksctl.io/nodegroup-name: ng2
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-4125-nodegroup-ng2/56247890-d4e7-11f0-83ea-12c4a7c69657
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-4125-nodegroup-ng2
          build_num: local
          creation_time: "2025-12-09T09:58:44Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-4125
          eksctl.io/v1alpha2/nodegroup-name: ng2
          email: automation@rafay.co
          env: automation
          squad: local
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-nodeg-NodeInstanceRole-lJ8y3CsxfVXm
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-nodeg-NodeInstanceRole-nGnrxaCL2ie2
        tags:
          Name: eksctl-rauto-eks-import-4125-nodegroup-ng1/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-4125
          alpha.eksctl.io/eksctl-version: 0.217.0
          alpha.eksctl.io/nodegroup-name: ng1
          alpha.eksctl.io/nodegroup-type: unmanaged
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-4125-nodegroup-ng1/56144bf0-d4e7-11f0-b3f9-0ec54ddfaff9
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-4125-nodegroup-ng1
          build_num: local
          creation_time: "2025-12-09T09:58:44Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-4125
          eksctl.io/v1alpha2/nodegroup-name: ng1
          email: automation@rafay.co
          env: automation
          squad: local
        type: EC2_LINUX
      - kubernetesGroups:
        - system:nodes
        kubernetesUsername: system:node:{{EC2PrivateDNSName}}
        principalARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-nodeg-NodeInstanceRole-oTX4TaZSbyGI
        type: EC2_LINUX
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/amarnath.savalgi@rafay.co
        principalARN: arn:aws:iam::211125364662:user/amarnath.savalgi@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: arn:aws:iam::211125364662:user/automation-user@rafay.co
        principalARN: arn:aws:iam::211125364662:user/automation-user@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: rautouser
        principalARN: arn:aws:iam::211125364662:user/kalyan@rafay.co
        tags:
          Name: eksctl-rauto-eks-import-4125-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V/AccessEntry
          alpha.eksctl.io/cluster-name: rauto-eks-import-4125
          alpha.eksctl.io/eksctl-version: 0.217.0
          aws:cloudformation:logical-id: AccessEntry
          aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:211125364662:stack/eksctl-rauto-eks-import-4125-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V/f4b737a0-d4e6-11f0-acc9-129a003f0a47
          aws:cloudformation:stack-name: eksctl-rauto-eks-import-4125-accessentry-YZY5DLDQ2SWAXOEGXCJXA4KDME3NTO2V
          build_num: local
          creation_time: "2025-12-09T09:58:44Z"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-4125
          email: automation@rafay.co
          env: automation
          squad: local
        type: STANDARD
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: v1.11.4-eksbuild.2
    - name: kube-proxy
      version: v1.32.6-eksbuild.12
    - name: metrics-server
      version: v0.8.0-eksbuild.5
    - name: vpc-cni
      version: v1.20.4-eksbuild.2
    addonsConfig: {}
    autoModeConfig: {}
    availabilityZones:
    - us-east-1a
    - us-east-1b
    iam:
      serviceAccounts:
      - metadata:
          name: default
          namespace: default
      - metadata:
          name: default
          namespace: default-rafay-master-sanity-automation
      - metadata:
          name: default
          namespace: kube-node-lease
      - metadata:
          name: default
          namespace: kube-public
      - metadata:
          name: attachdetach-controller
          namespace: kube-system
      - metadata:
          name: aws-cloud-provider
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: aws-vpc-cni
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: aws-node
            app.kubernetes.io/version: v1.20.4
            helm.sh/chart: aws-vpc-cni-1.20.4
            k8s-app: aws-node
          name: aws-node
          namespace: kube-system
      - metadata:
          name: certificate-controller
          namespace: kube-system
      - metadata:
          name: clusterrole-aggregation-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: coredns
            k8s-app: kube-dns
          name: coredns
          namespace: kube-system
      - metadata:
          name: cronjob-controller
          namespace: kube-system
      - metadata:
          name: daemon-set-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: kube-system
      - metadata:
          name: deployment-controller
          namespace: kube-system
      - metadata:
          name: disruption-controller
          namespace: kube-system
      - metadata:
          name: endpoint-controller
          namespace: kube-system
      - metadata:
          name: endpointslice-controller
          namespace: kube-system
      - metadata:
          name: endpointslicemirroring-controller
          namespace: kube-system
      - metadata:
          name: ephemeral-volume-controller
          namespace: kube-system
      - metadata:
          name: expand-controller
          namespace: kube-system
      - metadata:
          name: generic-garbage-collector
          namespace: kube-system
      - metadata:
          name: horizontal-pod-autoscaler
          namespace: kube-system
      - metadata:
          name: job-controller
          namespace: kube-system
      - metadata:
          labels:
            eks.amazonaws.com/component: kube-proxy
            k8s-app: kube-proxy
          name: kube-proxy
          namespace: kube-system
      - metadata:
          name: legacy-service-account-token-cleaner
          namespace: kube-system
      - metadata:
          labels:
            app.kubernetes.io/instance: metrics-server
            app.kubernetes.io/managed-by: EKS
            app.kubernetes.io/name: metrics-server
            app.kubernetes.io/version: 0.7.2
          name: metrics-server
          namespace: kube-system
      - metadata:
          name: namespace-controller
          namespace: kube-system
      - metadata:
          name: node-controller
          namespace: kube-system
      - metadata:
          name: persistent-volume-binder
          namespace: kube-system
      - metadata:
          name: pod-garbage-collector
          namespace: kube-system
      - metadata:
          name: pv-protection-controller
          namespace: kube-system
      - metadata:
          name: pvc-protection-controller
          namespace: kube-system
      - metadata:
          name: replicaset-controller
          namespace: kube-system
      - metadata:
          name: replication-controller
          namespace: kube-system
      - metadata:
          name: resourcequota-controller
          namespace: kube-system
      - metadata:
          name: root-ca-cert-publisher
          namespace: kube-system
      - metadata:
          name: service-account-controller
          namespace: kube-system
      - metadata:
          name: service-controller
          namespace: kube-system
      - metadata:
          name: statefulset-controller
          namespace: kube-system
      - metadata:
          name: tagging-controller
          namespace: kube-system
      - metadata:
          name: ttl-after-finished-controller
          namespace: kube-system
      - metadata:
          name: ttl-controller
          namespace: kube-system
      - metadata:
          name: validatingadmissionpolicy-status-controller
          namespace: kube-system
      - metadata:
          name: volumeattributesclass-protection-controller
          namespace: kube-system
      - metadata:
          name: default
          namespace: rafay-infra
      - metadata:
          labels:
            authz-expiry: "1765306497"
            authz-refreshed: "1765277697"
            k8smgmt.io/project: defaultproject
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: automation-45user-64rafay-46co
          name: automation-45user-64rafay-46co
          namespace: rafay-system
      - metadata:
          name: default
          namespace: rafay-system
      - metadata:
          labels:
            authz-expiry: "1765306506"
            authz-refreshed: "1765277706"
            rafay-permission: kubectl.fullaccess
            rafay-relay: "true"
            relay-user: rs-45admin-64rafay-46co
          name: rs-45admin-64rafay-46co
          namespace: rafay-system
      - metadata:
          labels:
            app.kubernetes.io/managed-by: Helm
            k8smgmt.io/project: defaultproject
            rep-addon: v2-infra
            rep-cluster: dk6gj02
            rep-cluster-name: rauto-eks-import-4125
            rep-drift-reconcillation: enabled
            rep-organization: 7dkgjkx
            rep-partner: q72dg2g
            rep-placement: j2qpo5k
            rep-project: 7w2lnkp
            rep-project-name: defaultproject
            rep-workloadid: lk5xw2e
          name: system-sa
          namespace: rafay-system
      serviceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-cluster-ServiceRole-KMLN1rq6qPzq
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      - us-east-1b
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-nodeg-NodeInstanceRole-lJ8y3CsxfVXm
      instanceType: t3.xlarge
      labels:
        alpha.eksctl.io/cluster-name: rauto-eks-import-4125
        alpha.eksctl.io/nodegroup-name: ng3
        key: rauto
      maxSize: 1
      minSize: 1
      name: ng3
      securityGroups:
        attachIDs:
        - sg-0b0888fbd466ebff4
      subnets:
      - subnet-04ed31d7fd7f837b6
      - subnet-0a2829a0882403f3d
      tags:
        Name: eksctl-rauto-eks-import-4125-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-4125
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: ng3
        alpha.eksctl.io/nodegroup-type: managed
        build_num: local
        creation_time: "2025-12-09T09:58:44Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-4125
        email: automation@rafay.co
        env: automation
        squad: local
      taints:
      - effect: NoSchedule
        key: nodetaint
        value: rauto
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      availabilityZones:
      - us-east-1a
      - us-east-1b
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::211125364662:role/eksctl-rauto-eks-import-4125-nodeg-NodeInstanceRole-oTX4TaZSbyGI
      instanceType: t3.xlarge
      labels:
        alpha.eksctl.io/cluster-name: rauto-eks-import-4125
        alpha.eksctl.io/nodegroup-name: ng4
      maxSize: 1
      minSize: 1
      name: ng4
      securityGroups:
        attachIDs:
        - sg-0b0888fbd466ebff4
      subnets:
      - subnet-04ed31d7fd7f837b6
      - subnet-0a2829a0882403f3d
      tags:
        Name: eksctl-rauto-eks-import-4125-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-4125
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.217.0
        alpha.eksctl.io/nodegroup-name: ng4
        alpha.eksctl.io/nodegroup-type: managed
        build_num: local
        creation_time: "2025-12-09T09:58:44Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-4125
        email: automation@rafay.co
        env: automation
        squad: local
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: rauto-eks-import-4125
      region: us-east-1
      tags:
        Name: eksctl-rauto-eks-import-4125-cluster/ControlPlane
        alpha.eksctl.io/cluster-name: rauto-eks-import-4125
        alpha.eksctl.io/cluster-oidc-enabled: "false"
        alpha.eksctl.io/eksctl-version: 0.217.0
        build_num: local
        creation_time: "2025-12-09T09:58:44Z"
        eksctl.cluster.k8s.io/v1alpha1/cluster-name: rauto-eks-import-4125
        email: automation@rafay.co
        env: automation
        squad: local
      version: "1.32"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      id: vpc-0fbab396220baf0c4
      securityGroup: sg-003859ff44cfa67d6
      sharedNodeSecurityGroup: sg-0b0888fbd466ebff4
      subnets:
        private:
          subnet-0ba4ac49feb8cb87b:
            id: subnet-0ba4ac49feb8cb87b
          subnet-0be60385e6b4c4388:
            id: subnet-0be60385e6b4c4388
        public:
          subnet-04ed31d7fd7f837b6:
            id: subnet-04ed31d7fd7f837b6
          subnet-0a2829a0882403f3d:
            id: subnet-0a2829a0882403f3d
  proxyConfig: {}
  systemComponentsPlacement: {}
  type: aws-eks
