---
kind: Cluster
metadata:
  name: cli-eksrauto-705764521
  project: rauto-eks-gitsync-2735
spec:
  blueprint: default
  cloudprovider: rauto_464160867
  type: eks
---
accessConfig:
  accessEntries:
  - accessPolicies:
    - accessScope:
        type: cluster
      policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
    kubernetesUsername: kalyan-rafay
    principalARN: arn:aws:iam::679196758854:user/kalyan@rafay.co
    type: STANDARD
  authenticationMode: API
  bootstrapClusterCreatorAdminPermissions: true
addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  version: latest
apiVersion: rafay.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1b
- us-east-1c
- us-east-1d
- us-east-1f
iam:
  serviceAccounts:
  - attachPolicy: {}
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    metadata:
      annotations:
        irsa: rauto-irsa
      labels:
        irsalabel: rauto-irsalabel
      name: rauto-irsa
      namespace: rafay-system
    tags:
      irsatag: rauto-irsatag
  withOIDC: true
kind: ClusterConfig
metadata:
  name: cli-eksrauto-705764521
  region: us-east-1
  tags:
    build_num: local
    creation_time: '2025-11-24T08:01:17Z'
    email: automation@rafay.co
    env: automation
    squad: local
  version: '1.32'
nodeGroups:
- amiFamily: AmazonLinux2023
  desiredCapacity: 1
  instanceType: t3.xlarge
  maxSize: 1
  minSize: 1
  name: cli-ngrauto-first-705764521
  privateNetworking: true
  version: '1.32'
- amiFamily: AmazonLinux2023
  desiredCapacity: 1
  instanceType: t3.xlarge
  maxSize: 1
  minSize: 1
  name: cli-ngrauto-second-705764521
  privateNetworking: true
  version: '1.32'
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
